
//input ports
add mapped point Datai[31] Datai[31] -type PI PI
add mapped point Datai[30] Datai[30] -type PI PI
add mapped point Datai[29] Datai[29] -type PI PI
add mapped point Datai[28] Datai[28] -type PI PI
add mapped point Datai[27] Datai[27] -type PI PI
add mapped point Datai[26] Datai[26] -type PI PI
add mapped point Datai[25] Datai[25] -type PI PI
add mapped point Datai[24] Datai[24] -type PI PI
add mapped point Datai[23] Datai[23] -type PI PI
add mapped point Datai[22] Datai[22] -type PI PI
add mapped point Datai[21] Datai[21] -type PI PI
add mapped point Datai[20] Datai[20] -type PI PI
add mapped point Datai[19] Datai[19] -type PI PI
add mapped point Datai[18] Datai[18] -type PI PI
add mapped point Datai[17] Datai[17] -type PI PI
add mapped point Datai[16] Datai[16] -type PI PI
add mapped point Datai[15] Datai[15] -type PI PI
add mapped point Datai[14] Datai[14] -type PI PI
add mapped point Datai[13] Datai[13] -type PI PI
add mapped point Datai[12] Datai[12] -type PI PI
add mapped point Datai[11] Datai[11] -type PI PI
add mapped point Datai[10] Datai[10] -type PI PI
add mapped point Datai[9] Datai[9] -type PI PI
add mapped point Datai[8] Datai[8] -type PI PI
add mapped point Datai[7] Datai[7] -type PI PI
add mapped point Datai[6] Datai[6] -type PI PI
add mapped point Datai[5] Datai[5] -type PI PI
add mapped point Datai[4] Datai[4] -type PI PI
add mapped point Datai[3] Datai[3] -type PI PI
add mapped point Datai[2] Datai[2] -type PI PI
add mapped point Datai[1] Datai[1] -type PI PI
add mapped point Datai[0] Datai[0] -type PI PI
add mapped point CLOCK CLOCK -type PI PI
add mapped point NA_n NA_n -type PI PI
add mapped point BS16_n BS16_n -type PI PI
add mapped point READY_n READY_n -type PI PI
add mapped point HOLD HOLD -type PI PI
add mapped point RESET RESET -type PI PI

//output ports
add mapped point BE_n[3] BE_n[3] -type PO PO
add mapped point BE_n[2] BE_n[2] -type PO PO
add mapped point BE_n[1] BE_n[1] -type PO PO
add mapped point BE_n[0] BE_n[0] -type PO PO
add mapped point Address[29] Address[29] -type PO PO
add mapped point Address[28] Address[28] -type PO PO
add mapped point Address[27] Address[27] -type PO PO
add mapped point Address[26] Address[26] -type PO PO
add mapped point Address[25] Address[25] -type PO PO
add mapped point Address[24] Address[24] -type PO PO
add mapped point Address[23] Address[23] -type PO PO
add mapped point Address[22] Address[22] -type PO PO
add mapped point Address[21] Address[21] -type PO PO
add mapped point Address[20] Address[20] -type PO PO
add mapped point Address[19] Address[19] -type PO PO
add mapped point Address[18] Address[18] -type PO PO
add mapped point Address[17] Address[17] -type PO PO
add mapped point Address[16] Address[16] -type PO PO
add mapped point Address[15] Address[15] -type PO PO
add mapped point Address[14] Address[14] -type PO PO
add mapped point Address[13] Address[13] -type PO PO
add mapped point Address[12] Address[12] -type PO PO
add mapped point Address[11] Address[11] -type PO PO
add mapped point Address[10] Address[10] -type PO PO
add mapped point Address[9] Address[9] -type PO PO
add mapped point Address[8] Address[8] -type PO PO
add mapped point Address[7] Address[7] -type PO PO
add mapped point Address[6] Address[6] -type PO PO
add mapped point Address[5] Address[5] -type PO PO
add mapped point Address[4] Address[4] -type PO PO
add mapped point Address[3] Address[3] -type PO PO
add mapped point Address[2] Address[2] -type PO PO
add mapped point Address[1] Address[1] -type PO PO
add mapped point Address[0] Address[0] -type PO PO
add mapped point W_R_n W_R_n -type PO PO
add mapped point D_C_n D_C_n -type PO PO
add mapped point M_IO_n M_IO_n -type PO PO
add mapped point ADS_n ADS_n -type PO PO
add mapped point Datao[31] Datao[31] -type PO PO
add mapped point Datao[30] Datao[30] -type PO PO
add mapped point Datao[29] Datao[29] -type PO PO
add mapped point Datao[28] Datao[28] -type PO PO
add mapped point Datao[27] Datao[27] -type PO PO
add mapped point Datao[26] Datao[26] -type PO PO
add mapped point Datao[25] Datao[25] -type PO PO
add mapped point Datao[24] Datao[24] -type PO PO
add mapped point Datao[23] Datao[23] -type PO PO
add mapped point Datao[22] Datao[22] -type PO PO
add mapped point Datao[21] Datao[21] -type PO PO
add mapped point Datao[20] Datao[20] -type PO PO
add mapped point Datao[19] Datao[19] -type PO PO
add mapped point Datao[18] Datao[18] -type PO PO
add mapped point Datao[17] Datao[17] -type PO PO
add mapped point Datao[16] Datao[16] -type PO PO
add mapped point Datao[15] Datao[15] -type PO PO
add mapped point Datao[14] Datao[14] -type PO PO
add mapped point Datao[13] Datao[13] -type PO PO
add mapped point Datao[12] Datao[12] -type PO PO
add mapped point Datao[11] Datao[11] -type PO PO
add mapped point Datao[10] Datao[10] -type PO PO
add mapped point Datao[9] Datao[9] -type PO PO
add mapped point Datao[8] Datao[8] -type PO PO
add mapped point Datao[7] Datao[7] -type PO PO
add mapped point Datao[6] Datao[6] -type PO PO
add mapped point Datao[5] Datao[5] -type PO PO
add mapped point Datao[4] Datao[4] -type PO PO
add mapped point Datao[3] Datao[3] -type PO PO
add mapped point Datao[2] Datao[2] -type PO PO
add mapped point Datao[1] Datao[1] -type PO PO
add mapped point Datao[0] Datao[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point ADS_n/q ADS_n_reg/Q  -type DFF DFF
add mapped point Address[0]/q Address_reg[0]/Q  -type DFF DFF
add mapped point Address[1]/q Address_reg[1]/Q  -type DFF DFF
add mapped point Address[2]/q Address_reg[2]/Q  -type DFF DFF
add mapped point Address[3]/q Address_reg[3]/Q  -type DFF DFF
add mapped point Address[4]/q Address_reg[4]/Q  -type DFF DFF
add mapped point Address[5]/q Address_reg[5]/Q  -type DFF DFF
add mapped point Address[6]/q Address_reg[6]/Q  -type DFF DFF
add mapped point Address[7]/q Address_reg[7]/Q  -type DFF DFF
add mapped point Address[8]/q Address_reg[8]/Q  -type DFF DFF
add mapped point Address[9]/q Address_reg[9]/Q  -type DFF DFF
add mapped point Address[10]/q Address_reg[10]/Q  -type DFF DFF
add mapped point Address[11]/q Address_reg[11]/Q  -type DFF DFF
add mapped point Address[12]/q Address_reg[12]/Q  -type DFF DFF
add mapped point Address[13]/q Address_reg[13]/Q  -type DFF DFF
add mapped point Address[14]/q Address_reg[14]/Q  -type DFF DFF
add mapped point Address[15]/q Address_reg[15]/Q  -type DFF DFF
add mapped point Address[16]/q Address_reg[16]/Q  -type DFF DFF
add mapped point Address[17]/q Address_reg[17]/Q  -type DFF DFF
add mapped point Address[18]/q Address_reg[18]/Q  -type DFF DFF
add mapped point Address[19]/q Address_reg[19]/Q  -type DFF DFF
add mapped point Address[20]/q Address_reg[20]/Q  -type DFF DFF
add mapped point Address[21]/q Address_reg[21]/Q  -type DFF DFF
add mapped point Address[22]/q Address_reg[22]/Q  -type DFF DFF
add mapped point Address[23]/q Address_reg[23]/Q  -type DFF DFF
add mapped point Address[24]/q Address_reg[24]/Q  -type DFF DFF
add mapped point Address[25]/q Address_reg[25]/Q  -type DFF DFF
add mapped point Address[26]/q Address_reg[26]/Q  -type DFF DFF
add mapped point Address[27]/q Address_reg[27]/Q  -type DFF DFF
add mapped point Address[28]/q Address_reg[28]/Q  -type DFF DFF
add mapped point Address[29]/q Address_reg[29]/Q  -type DFF DFF
add mapped point BE_n[0]/q BE_n_reg[0]/Q  -type DFF DFF
add mapped point BE_n[1]/q BE_n_reg[1]/Q  -type DFF DFF
add mapped point BE_n[2]/q BE_n_reg[2]/Q  -type DFF DFF
add mapped point BE_n[3]/q BE_n_reg[3]/Q  -type DFF DFF
add mapped point ByteEnable[0]/q ByteEnable_reg[0]/Q  -type DFF DFF
add mapped point ByteEnable[2]/q ByteEnable_reg[2]/Q  -type DFF DFF
add mapped point ByteEnable[3]/q ByteEnable_reg[3]/Q  -type DFF DFF
add mapped point CodeFetch/q CodeFetch_reg/Q  -type DFF DFF
add mapped point D_C_n/q D_C_n_reg/Q  -type DFF DFF
add mapped point DataWidth[0]/q DataWidth_reg[0]/Q  -type DFF DFF
add mapped point Datao[0]/q Datao_reg[0]/Q  -type DFF DFF
add mapped point Datao[1]/q Datao_reg[1]/Q  -type DFF DFF
add mapped point Datao[2]/q Datao_reg[2]/Q  -type DFF DFF
add mapped point Datao[3]/q Datao_reg[3]/Q  -type DFF DFF
add mapped point Datao[4]/q Datao_reg[4]/Q  -type DFF DFF
add mapped point Datao[5]/q Datao_reg[5]/Q  -type DFF DFF
add mapped point Datao[6]/q Datao_reg[6]/Q  -type DFF DFF
add mapped point Datao[7]/q Datao_reg[7]/Q  -type DFF DFF
add mapped point Datao[8]/q Datao_reg[8]/Q  -type DFF DFF
add mapped point Datao[9]/q Datao_reg[9]/Q  -type DFF DFF
add mapped point Datao[10]/q Datao_reg[10]/Q  -type DFF DFF
add mapped point Datao[11]/q Datao_reg[11]/Q  -type DFF DFF
add mapped point Datao[12]/q Datao_reg[12]/Q  -type DFF DFF
add mapped point Datao[13]/q Datao_reg[13]/Q  -type DFF DFF
add mapped point Datao[14]/q Datao_reg[14]/Q  -type DFF DFF
add mapped point Datao[15]/q Datao_reg[15]/Q  -type DFF DFF
add mapped point Datao[16]/q Datao_reg[16]/Q  -type DFF DFF
add mapped point Datao[17]/q Datao_reg[17]/Q  -type DFF DFF
add mapped point Datao[18]/q Datao_reg[18]/Q  -type DFF DFF
add mapped point Datao[19]/q Datao_reg[19]/Q  -type DFF DFF
add mapped point Datao[20]/q Datao_reg[20]/Q  -type DFF DFF
add mapped point Datao[21]/q Datao_reg[21]/Q  -type DFF DFF
add mapped point Datao[22]/q Datao_reg[22]/Q  -type DFF DFF
add mapped point Datao[23]/q Datao_reg[23]/Q  -type DFF DFF
add mapped point Datao[24]/q Datao_reg[24]/Q  -type DFF DFF
add mapped point Datao[25]/q Datao_reg[25]/Q  -type DFF DFF
add mapped point Datao[26]/q Datao_reg[26]/Q  -type DFF DFF
add mapped point Datao[27]/q Datao_reg[27]/Q  -type DFF DFF
add mapped point Datao[28]/q Datao_reg[28]/Q  -type DFF DFF
add mapped point Datao[29]/q Datao_reg[29]/Q  -type DFF DFF
add mapped point Datao[30]/q Datao_reg[30]/Q  -type DFF DFF
add mapped point EAX[0]/q EAX_reg[0]/Q  -type DFF DFF
add mapped point EAX[0]/q EAX_reg[0]/QN  -type DFF DFF
add mapped point EAX[1]/q EAX_reg[1]/Q  -type DFF DFF
add mapped point EAX[2]/q EAX_reg[2]/Q  -type DFF DFF
add mapped point EAX[2]/q EAX_reg[2]/QN  -type DFF DFF
add mapped point EAX[4]/q EAX_reg[4]/Q  -type DFF DFF
add mapped point EAX[4]/q EAX_reg[4]/QN  -type DFF DFF
add mapped point EAX[5]/q EAX_reg[5]/Q  -type DFF DFF
add mapped point EAX[5]/q EAX_reg[5]/QN  -type DFF DFF
add mapped point EAX[6]/q EAX_reg[6]/Q  -type DFF DFF
add mapped point EAX[6]/q EAX_reg[6]/QN  -type DFF DFF
add mapped point EAX[8]/q EAX_reg[8]/Q  -type DFF DFF
add mapped point EAX[8]/q EAX_reg[8]/QN  -type DFF DFF
add mapped point EAX[9]/q EAX_reg[9]/Q  -type DFF DFF
add mapped point EAX[9]/q EAX_reg[9]/QN  -type DFF DFF
add mapped point EAX[10]/q EAX_reg[10]/Q  -type DFF DFF
add mapped point EAX[10]/q EAX_reg[10]/QN  -type DFF DFF
add mapped point EAX[12]/q EAX_reg[12]/Q  -type DFF DFF
add mapped point EAX[12]/q EAX_reg[12]/QN  -type DFF DFF
add mapped point EAX[13]/q EAX_reg[13]/Q  -type DFF DFF
add mapped point EAX[13]/q EAX_reg[13]/QN  -type DFF DFF
add mapped point EAX[14]/q EAX_reg[14]/Q  -type DFF DFF
add mapped point EAX[14]/q EAX_reg[14]/QN  -type DFF DFF
add mapped point EAX[19]/q EAX_reg[19]/Q  -type DFF DFF
add mapped point EAX[21]/q EAX_reg[21]/Q  -type DFF DFF
add mapped point EAX[24]/q EAX_reg[24]/Q  -type DFF DFF
add mapped point EAX[24]/q EAX_reg[24]/QN  -type DFF DFF
add mapped point EAX[25]/q EAX_reg[25]/Q  -type DFF DFF
add mapped point EAX[25]/q EAX_reg[25]/QN  -type DFF DFF
add mapped point EAX[26]/q EAX_reg[26]/Q  -type DFF DFF
add mapped point EAX[26]/q EAX_reg[26]/QN  -type DFF DFF
add mapped point EAX[29]/q EAX_reg[29]/Q  -type DFF DFF
add mapped point EAX[30]/q EAX_reg[30]/Q  -type DFF DFF
add mapped point EAX[31]/q EAX_reg[31]/Q  -type DFF DFF
add mapped point P1.Flush/q Flush_reg/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[0]/q InstAddrPointer_reg[0]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[1]/q InstAddrPointer_reg[1]/Q  -type DFF DFF
add mapped point P1.InstQueueRd_Addr[1]/q InstQueueRd_Addr_reg[1]/Q  -type DFF DFF
add mapped point P1.InstQueueRd_Addr[2]/q InstQueueRd_Addr_reg[2]/Q  -type DFF DFF
add mapped point P1.InstQueueRd_Addr[3]/q InstQueueRd_Addr_reg[3]/Q  -type DFF DFF
add mapped point P1.InstQueueWr_Addr[0]/q InstQueueWr_Addr_reg[0]/Q  -type DFF DFF
add mapped point P1.InstQueueWr_Addr[0]/q InstQueueWr_Addr_reg[0]/QN  -type DFF DFF
add mapped point P1.InstQueueWr_Addr[1]/q InstQueueWr_Addr_reg[1]/Q  -type DFF DFF
add mapped point P1.InstQueueWr_Addr[2]/q InstQueueWr_Addr_reg[2]/Q  -type DFF DFF
add mapped point P1.InstQueue[0][0]/q InstQueue_reg[0][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[0][1]/q InstQueue_reg[0][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[0][2]/q InstQueue_reg[0][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[0][3]/q InstQueue_reg[0][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[0][4]/q InstQueue_reg[0][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[0][5]/q InstQueue_reg[0][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[0][6]/q InstQueue_reg[0][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[0][7]/q InstQueue_reg[0][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[1][0]/q InstQueue_reg[1][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[1][1]/q InstQueue_reg[1][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[1][2]/q InstQueue_reg[1][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[1][3]/q InstQueue_reg[1][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[1][4]/q InstQueue_reg[1][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[1][5]/q InstQueue_reg[1][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[1][6]/q InstQueue_reg[1][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[1][7]/q InstQueue_reg[1][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[2][0]/q InstQueue_reg[2][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[2][1]/q InstQueue_reg[2][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[2][2]/q InstQueue_reg[2][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[2][3]/q InstQueue_reg[2][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[2][4]/q InstQueue_reg[2][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[2][5]/q InstQueue_reg[2][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[2][6]/q InstQueue_reg[2][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[2][7]/q InstQueue_reg[2][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[3][0]/q InstQueue_reg[3][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[3][1]/q InstQueue_reg[3][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[3][2]/q InstQueue_reg[3][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[3][3]/q InstQueue_reg[3][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[3][4]/q InstQueue_reg[3][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[3][5]/q InstQueue_reg[3][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[3][6]/q InstQueue_reg[3][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[3][7]/q InstQueue_reg[3][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[4][0]/q InstQueue_reg[4][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[4][1]/q InstQueue_reg[4][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[4][2]/q InstQueue_reg[4][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[4][3]/q InstQueue_reg[4][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[4][4]/q InstQueue_reg[4][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[4][5]/q InstQueue_reg[4][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[4][6]/q InstQueue_reg[4][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[4][7]/q InstQueue_reg[4][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[5][0]/q InstQueue_reg[5][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[5][1]/q InstQueue_reg[5][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[5][2]/q InstQueue_reg[5][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[5][3]/q InstQueue_reg[5][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[5][4]/q InstQueue_reg[5][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[5][5]/q InstQueue_reg[5][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[5][6]/q InstQueue_reg[5][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[5][7]/q InstQueue_reg[5][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[6][0]/q InstQueue_reg[6][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[6][1]/q InstQueue_reg[6][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[6][2]/q InstQueue_reg[6][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[6][3]/q InstQueue_reg[6][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[6][4]/q InstQueue_reg[6][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[6][5]/q InstQueue_reg[6][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[6][6]/q InstQueue_reg[6][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[6][7]/q InstQueue_reg[6][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[7][0]/q InstQueue_reg[7][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[7][1]/q InstQueue_reg[7][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[7][2]/q InstQueue_reg[7][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[7][3]/q InstQueue_reg[7][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[7][4]/q InstQueue_reg[7][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[7][5]/q InstQueue_reg[7][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[7][6]/q InstQueue_reg[7][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[7][7]/q InstQueue_reg[7][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[8][0]/q InstQueue_reg[8][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[8][1]/q InstQueue_reg[8][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[8][2]/q InstQueue_reg[8][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[8][3]/q InstQueue_reg[8][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[8][4]/q InstQueue_reg[8][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[8][5]/q InstQueue_reg[8][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[8][6]/q InstQueue_reg[8][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[8][7]/q InstQueue_reg[8][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[9][0]/q InstQueue_reg[9][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[9][1]/q InstQueue_reg[9][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[9][2]/q InstQueue_reg[9][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[9][3]/q InstQueue_reg[9][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[9][4]/q InstQueue_reg[9][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[9][5]/q InstQueue_reg[9][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[9][6]/q InstQueue_reg[9][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[9][7]/q InstQueue_reg[9][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[10][0]/q InstQueue_reg[10][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[10][1]/q InstQueue_reg[10][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[10][2]/q InstQueue_reg[10][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[10][3]/q InstQueue_reg[10][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[10][4]/q InstQueue_reg[10][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[10][5]/q InstQueue_reg[10][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[10][6]/q InstQueue_reg[10][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[10][7]/q InstQueue_reg[10][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[11][0]/q InstQueue_reg[11][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[11][1]/q InstQueue_reg[11][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[11][2]/q InstQueue_reg[11][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[11][3]/q InstQueue_reg[11][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[11][4]/q InstQueue_reg[11][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[11][5]/q InstQueue_reg[11][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[11][6]/q InstQueue_reg[11][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[11][7]/q InstQueue_reg[11][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[12][0]/q InstQueue_reg[12][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[12][1]/q InstQueue_reg[12][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[12][2]/q InstQueue_reg[12][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[12][3]/q InstQueue_reg[12][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[12][4]/q InstQueue_reg[12][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[12][5]/q InstQueue_reg[12][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[12][6]/q InstQueue_reg[12][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[12][7]/q InstQueue_reg[12][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[13][0]/q InstQueue_reg[13][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[13][1]/q InstQueue_reg[13][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[13][2]/q InstQueue_reg[13][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[13][3]/q InstQueue_reg[13][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[13][4]/q InstQueue_reg[13][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[13][5]/q InstQueue_reg[13][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[13][6]/q InstQueue_reg[13][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[13][7]/q InstQueue_reg[13][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[14][0]/q InstQueue_reg[14][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[14][1]/q InstQueue_reg[14][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[14][2]/q InstQueue_reg[14][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[14][3]/q InstQueue_reg[14][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[14][4]/q InstQueue_reg[14][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[14][5]/q InstQueue_reg[14][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[14][6]/q InstQueue_reg[14][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[14][7]/q InstQueue_reg[14][7]/Q  -type DFF DFF
add mapped point P1.InstQueue[15][0]/q InstQueue_reg[15][0]/Q  -type DFF DFF
add mapped point P1.InstQueue[15][1]/q InstQueue_reg[15][1]/Q  -type DFF DFF
add mapped point P1.InstQueue[15][2]/q InstQueue_reg[15][2]/Q  -type DFF DFF
add mapped point P1.InstQueue[15][3]/q InstQueue_reg[15][3]/Q  -type DFF DFF
add mapped point P1.InstQueue[15][4]/q InstQueue_reg[15][4]/Q  -type DFF DFF
add mapped point P1.InstQueue[15][5]/q InstQueue_reg[15][5]/Q  -type DFF DFF
add mapped point P1.InstQueue[15][6]/q InstQueue_reg[15][6]/Q  -type DFF DFF
add mapped point P1.InstQueue[15][7]/q InstQueue_reg[15][7]/Q  -type DFF DFF
add mapped point M_IO_n/q M_IO_n_reg/Q  -type DFF DFF
add mapped point MemoryFetch/q MemoryFetch_reg/Q  -type DFF DFF
add mapped point P1.More/q More_reg/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[0]/q PhyAddrPointer_reg[0]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[1]/q PhyAddrPointer_reg[1]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[1]/q PhyAddrPointer_reg[1]/QN  -type DFF DFF
add mapped point P1.PhyAddrPointer[3]/q PhyAddrPointer_reg[3]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[3]/q PhyAddrPointer_reg[3]/QN  -type DFF DFF
add mapped point P1.PhyAddrPointer[31]/q PhyAddrPointer_reg[31]/Q  -type DFF DFF
add mapped point ReadRequest/q ReadRequest_reg/Q  -type DFF DFF
add mapped point RequestPending/q RequestPending_reg/Q  -type DFF DFF
add mapped point P1.State2[1]/q State2_reg[1]/Q  -type DFF DFF
add mapped point P1.State2[2]/q State2_reg[2]/Q  -type DFF DFF
add mapped point P1.State2[2]/q State2_reg[2]/QN  -type DFF DFF
add mapped point P1.State2[3]/q State2_reg[3]/Q  -type DFF DFF
add mapped point P1.State2[3]/q State2_reg[3]/QN  -type DFF DFF
add mapped point State[0]/q State_reg[0]/Q  -type DFF DFF
add mapped point State[0]/q State_reg[0]/QN  -type DFF DFF
add mapped point State[1]/q State_reg[1]/Q  -type DFF DFF
add mapped point State[1]/q State_reg[1]/QN  -type DFF DFF
add mapped point W_R_n/q W_R_n_reg/Q  -type DFF DFF
add mapped point P1.lWord[0]/q lWord_reg[0]/Q  -type DFF DFF
add mapped point P1.lWord[1]/q lWord_reg[1]/Q  -type DFF DFF
add mapped point P1.lWord[2]/q lWord_reg[2]/Q  -type DFF DFF
add mapped point P1.lWord[3]/q lWord_reg[3]/Q  -type DFF DFF
add mapped point P1.lWord[4]/q lWord_reg[4]/Q  -type DFF DFF
add mapped point P1.lWord[5]/q lWord_reg[5]/Q  -type DFF DFF
add mapped point P1.lWord[6]/q lWord_reg[6]/Q  -type DFF DFF
add mapped point P1.lWord[7]/q lWord_reg[7]/Q  -type DFF DFF
add mapped point P1.lWord[8]/q lWord_reg[8]/Q  -type DFF DFF
add mapped point P1.lWord[9]/q lWord_reg[9]/Q  -type DFF DFF
add mapped point P1.lWord[10]/q lWord_reg[10]/Q  -type DFF DFF
add mapped point P1.lWord[11]/q lWord_reg[11]/Q  -type DFF DFF
add mapped point P1.lWord[12]/q lWord_reg[12]/Q  -type DFF DFF
add mapped point P1.lWord[13]/q lWord_reg[13]/Q  -type DFF DFF
add mapped point P1.lWord[14]/q lWord_reg[14]/Q  -type DFF DFF
add mapped point P1.lWord[15]/q lWord_reg[15]/Q  -type DFF DFF
add mapped point rEIP[0]/q rEIP_reg[0]/Q  -type DFF DFF
add mapped point rEIP[1]/q rEIP_reg[1]/Q  -type DFF DFF
add mapped point rEIP[1]/q rEIP_reg[1]/QN  -type DFF DFF
add mapped point rEIP[2]/q rEIP_reg[2]/Q  -type DFF DFF
add mapped point rEIP[3]/q rEIP_reg[3]/Q  -type DFF DFF
add mapped point rEIP[4]/q rEIP_reg[4]/Q  -type DFF DFF
add mapped point rEIP[5]/q rEIP_reg[5]/Q  -type DFF DFF
add mapped point rEIP[6]/q rEIP_reg[6]/Q  -type DFF DFF
add mapped point rEIP[7]/q rEIP_reg[7]/Q  -type DFF DFF
add mapped point rEIP[8]/q rEIP_reg[8]/Q  -type DFF DFF
add mapped point rEIP[9]/q rEIP_reg[9]/Q  -type DFF DFF
add mapped point rEIP[10]/q rEIP_reg[10]/Q  -type DFF DFF
add mapped point rEIP[11]/q rEIP_reg[11]/Q  -type DFF DFF
add mapped point rEIP[12]/q rEIP_reg[12]/Q  -type DFF DFF
add mapped point rEIP[13]/q rEIP_reg[13]/Q  -type DFF DFF
add mapped point rEIP[14]/q rEIP_reg[14]/Q  -type DFF DFF
add mapped point rEIP[15]/q rEIP_reg[15]/Q  -type DFF DFF
add mapped point rEIP[16]/q rEIP_reg[16]/Q  -type DFF DFF
add mapped point rEIP[17]/q rEIP_reg[17]/Q  -type DFF DFF
add mapped point rEIP[18]/q rEIP_reg[18]/Q  -type DFF DFF
add mapped point rEIP[19]/q rEIP_reg[19]/Q  -type DFF DFF
add mapped point rEIP[20]/q rEIP_reg[20]/Q  -type DFF DFF
add mapped point rEIP[21]/q rEIP_reg[21]/Q  -type DFF DFF
add mapped point rEIP[22]/q rEIP_reg[22]/Q  -type DFF DFF
add mapped point rEIP[23]/q rEIP_reg[23]/Q  -type DFF DFF
add mapped point rEIP[24]/q rEIP_reg[24]/Q  -type DFF DFF
add mapped point rEIP[25]/q rEIP_reg[25]/Q  -type DFF DFF
add mapped point rEIP[26]/q rEIP_reg[26]/Q  -type DFF DFF
add mapped point rEIP[27]/q rEIP_reg[27]/Q  -type DFF DFF
add mapped point rEIP[28]/q rEIP_reg[28]/Q  -type DFF DFF
add mapped point rEIP[29]/q rEIP_reg[29]/Q  -type DFF DFF
add mapped point rEIP[30]/q rEIP_reg[30]/Q  -type DFF DFF
add mapped point rEIP[31]/q rEIP_reg[31]/Q  -type DFF DFF
add mapped point P1.uWord[0]/q uWord_reg[0]/Q  -type DFF DFF
add mapped point P1.uWord[1]/q uWord_reg[1]/Q  -type DFF DFF
add mapped point P1.uWord[2]/q uWord_reg[2]/Q  -type DFF DFF
add mapped point P1.uWord[3]/q uWord_reg[3]/Q  -type DFF DFF
add mapped point P1.uWord[4]/q uWord_reg[4]/Q  -type DFF DFF
add mapped point P1.uWord[5]/q uWord_reg[5]/Q  -type DFF DFF
add mapped point P1.uWord[6]/q uWord_reg[6]/Q  -type DFF DFF
add mapped point P1.uWord[7]/q uWord_reg[7]/Q  -type DFF DFF
add mapped point P1.uWord[8]/q uWord_reg[8]/Q  -type DFF DFF
add mapped point P1.uWord[9]/q uWord_reg[9]/Q  -type DFF DFF
add mapped point P1.uWord[10]/q uWord_reg[10]/Q  -type DFF DFF
add mapped point P1.uWord[11]/q uWord_reg[11]/Q  -type DFF DFF
add mapped point P1.uWord[12]/q uWord_reg[12]/Q  -type DFF DFF
add mapped point P1.uWord[13]/q uWord_reg[13]/Q  -type DFF DFF
add mapped point P1.uWord[14]/q uWord_reg[14]/Q  -type DFF DFF
add mapped point ByteEnable[1]/q ByteEnable_reg[1]/Q  -type DFF DFF
add mapped point ByteEnable[1]/q ByteEnable_reg[1]/QN  -type DFF DFF
add mapped point DataWidth[1]/q DataWidth_reg[1]/Q  -type DFF DFF
add mapped point DataWidth[1]/q DataWidth_reg[1]/QN  -type DFF DFF
add mapped point EAX[3]/q EAX_reg[3]/Q  -type DFF DFF
add mapped point EAX[3]/q EAX_reg[3]/QN  -type DFF DFF
add mapped point EAX[7]/q EAX_reg[7]/Q  -type DFF DFF
add mapped point EAX[7]/q EAX_reg[7]/QN  -type DFF DFF
add mapped point EAX[11]/q EAX_reg[11]/Q  -type DFF DFF
add mapped point EAX[11]/q EAX_reg[11]/QN  -type DFF DFF
add mapped point EAX[15]/q EAX_reg[15]/Q  -type DFF DFF
add mapped point EAX[15]/q EAX_reg[15]/QN  -type DFF DFF
add mapped point EAX[16]/q EAX_reg[16]/Q  -type DFF DFF
add mapped point EAX[17]/q EAX_reg[17]/Q  -type DFF DFF
add mapped point EAX[18]/q EAX_reg[18]/Q  -type DFF DFF
add mapped point EAX[20]/q EAX_reg[20]/Q  -type DFF DFF
add mapped point EAX[22]/q EAX_reg[22]/Q  -type DFF DFF
add mapped point EAX[23]/q EAX_reg[23]/Q  -type DFF DFF
add mapped point EAX[23]/q EAX_reg[23]/QN  -type DFF DFF
add mapped point EAX[27]/q EAX_reg[27]/Q  -type DFF DFF
add mapped point EAX[27]/q EAX_reg[27]/QN  -type DFF DFF
add mapped point EAX[28]/q EAX_reg[28]/Q  -type DFF DFF
add mapped point EAX[28]/q EAX_reg[28]/QN  -type DFF DFF
add mapped point EBX[0]/q EBX_reg[0]/Q  -type DFF DFF
add mapped point EBX[1]/q EBX_reg[1]/Q  -type DFF DFF
add mapped point EBX[2]/q EBX_reg[2]/Q  -type DFF DFF
add mapped point EBX[3]/q EBX_reg[3]/Q  -type DFF DFF
add mapped point EBX[4]/q EBX_reg[4]/Q  -type DFF DFF
add mapped point EBX[5]/q EBX_reg[5]/Q  -type DFF DFF
add mapped point EBX[6]/q EBX_reg[6]/Q  -type DFF DFF
add mapped point EBX[7]/q EBX_reg[7]/Q  -type DFF DFF
add mapped point EBX[8]/q EBX_reg[8]/Q  -type DFF DFF
add mapped point EBX[9]/q EBX_reg[9]/Q  -type DFF DFF
add mapped point EBX[10]/q EBX_reg[10]/Q  -type DFF DFF
add mapped point EBX[11]/q EBX_reg[11]/Q  -type DFF DFF
add mapped point EBX[12]/q EBX_reg[12]/Q  -type DFF DFF
add mapped point EBX[13]/q EBX_reg[13]/Q  -type DFF DFF
add mapped point EBX[14]/q EBX_reg[14]/Q  -type DFF DFF
add mapped point EBX[15]/q EBX_reg[15]/Q  -type DFF DFF
add mapped point EBX[16]/q EBX_reg[16]/Q  -type DFF DFF
add mapped point EBX[17]/q EBX_reg[17]/Q  -type DFF DFF
add mapped point EBX[18]/q EBX_reg[18]/Q  -type DFF DFF
add mapped point EBX[19]/q EBX_reg[19]/Q  -type DFF DFF
add mapped point EBX[20]/q EBX_reg[20]/Q  -type DFF DFF
add mapped point EBX[21]/q EBX_reg[21]/Q  -type DFF DFF
add mapped point EBX[22]/q EBX_reg[22]/Q  -type DFF DFF
add mapped point EBX[23]/q EBX_reg[23]/Q  -type DFF DFF
add mapped point EBX[24]/q EBX_reg[24]/Q  -type DFF DFF
add mapped point EBX[25]/q EBX_reg[25]/Q  -type DFF DFF
add mapped point EBX[26]/q EBX_reg[26]/Q  -type DFF DFF
add mapped point EBX[27]/q EBX_reg[27]/Q  -type DFF DFF
add mapped point EBX[28]/q EBX_reg[28]/Q  -type DFF DFF
add mapped point EBX[29]/q EBX_reg[29]/Q  -type DFF DFF
add mapped point EBX[30]/q EBX_reg[30]/Q  -type DFF DFF
add mapped point EBX[31]/q EBX_reg[31]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[2]/q InstAddrPointer_reg[2]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[3]/q InstAddrPointer_reg[3]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[4]/q InstAddrPointer_reg[4]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[5]/q InstAddrPointer_reg[5]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[6]/q InstAddrPointer_reg[6]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[7]/q InstAddrPointer_reg[7]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[8]/q InstAddrPointer_reg[8]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[9]/q InstAddrPointer_reg[9]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[10]/q InstAddrPointer_reg[10]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[11]/q InstAddrPointer_reg[11]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[12]/q InstAddrPointer_reg[12]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[13]/q InstAddrPointer_reg[13]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[14]/q InstAddrPointer_reg[14]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[15]/q InstAddrPointer_reg[15]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[16]/q InstAddrPointer_reg[16]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[17]/q InstAddrPointer_reg[17]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[18]/q InstAddrPointer_reg[18]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[19]/q InstAddrPointer_reg[19]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[20]/q InstAddrPointer_reg[20]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[21]/q InstAddrPointer_reg[21]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[22]/q InstAddrPointer_reg[22]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[23]/q InstAddrPointer_reg[23]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[24]/q InstAddrPointer_reg[24]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[25]/q InstAddrPointer_reg[25]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[26]/q InstAddrPointer_reg[26]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[27]/q InstAddrPointer_reg[27]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[28]/q InstAddrPointer_reg[28]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[29]/q InstAddrPointer_reg[29]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[30]/q InstAddrPointer_reg[30]/Q  -type DFF DFF
add mapped point P1.InstAddrPointer[31]/q InstAddrPointer_reg[31]/Q  -type DFF DFF
add mapped point P1.InstQueueRd_Addr[0]/q InstQueueRd_Addr_reg[0]/Q  -type DFF DFF
add mapped point P1.InstQueueRd_Addr[0]/q InstQueueRd_Addr_reg[0]/QN  -type DFF DFF
add mapped point P1.InstQueueWr_Addr[3]/q InstQueueWr_Addr_reg[3]/Q  -type DFF DFF
add mapped point P1.InstQueueWr_Addr[3]/q InstQueueWr_Addr_reg[3]/QN  -type DFF DFF
add mapped point P1.PhyAddrPointer[2]/q PhyAddrPointer_reg[2]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[4]/q PhyAddrPointer_reg[4]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[5]/q PhyAddrPointer_reg[5]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[6]/q PhyAddrPointer_reg[6]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[7]/q PhyAddrPointer_reg[7]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[8]/q PhyAddrPointer_reg[8]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[9]/q PhyAddrPointer_reg[9]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[10]/q PhyAddrPointer_reg[10]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[11]/q PhyAddrPointer_reg[11]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[12]/q PhyAddrPointer_reg[12]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[13]/q PhyAddrPointer_reg[13]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[14]/q PhyAddrPointer_reg[14]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[15]/q PhyAddrPointer_reg[15]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[16]/q PhyAddrPointer_reg[16]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[17]/q PhyAddrPointer_reg[17]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[18]/q PhyAddrPointer_reg[18]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[19]/q PhyAddrPointer_reg[19]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[20]/q PhyAddrPointer_reg[20]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[21]/q PhyAddrPointer_reg[21]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[22]/q PhyAddrPointer_reg[22]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[23]/q PhyAddrPointer_reg[23]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[24]/q PhyAddrPointer_reg[24]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[25]/q PhyAddrPointer_reg[25]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[26]/q PhyAddrPointer_reg[26]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[27]/q PhyAddrPointer_reg[27]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[28]/q PhyAddrPointer_reg[28]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[29]/q PhyAddrPointer_reg[29]/Q  -type DFF DFF
add mapped point P1.PhyAddrPointer[30]/q PhyAddrPointer_reg[30]/Q  -type DFF DFF
add mapped point P1.State2[0]/q State2_reg[0]/Q  -type DFF DFF
add mapped point P1.State2[0]/q State2_reg[0]/QN  -type DFF DFF
add mapped point State[2]/q State_reg[2]/Q  -type DFF DFF
add mapped point State[2]/q State_reg[2]/QN  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
