
//input ports
add mapped point clock clock -type PI PI
add mapped point reset reset -type PI PI
add mapped point datai[31] datai[31] -type PI PI
add mapped point datai[30] datai[30] -type PI PI
add mapped point datai[29] datai[29] -type PI PI
add mapped point datai[28] datai[28] -type PI PI
add mapped point datai[27] datai[27] -type PI PI
add mapped point datai[26] datai[26] -type PI PI
add mapped point datai[25] datai[25] -type PI PI
add mapped point datai[24] datai[24] -type PI PI
add mapped point datai[23] datai[23] -type PI PI
add mapped point datai[22] datai[22] -type PI PI
add mapped point datai[21] datai[21] -type PI PI
add mapped point datai[20] datai[20] -type PI PI
add mapped point datai[19] datai[19] -type PI PI
add mapped point datai[18] datai[18] -type PI PI
add mapped point datai[17] datai[17] -type PI PI
add mapped point datai[16] datai[16] -type PI PI
add mapped point datai[15] datai[15] -type PI PI
add mapped point datai[14] datai[14] -type PI PI
add mapped point datai[13] datai[13] -type PI PI
add mapped point datai[12] datai[12] -type PI PI
add mapped point datai[11] datai[11] -type PI PI
add mapped point datai[10] datai[10] -type PI PI
add mapped point datai[9] datai[9] -type PI PI
add mapped point datai[8] datai[8] -type PI PI
add mapped point datai[7] datai[7] -type PI PI
add mapped point datai[6] datai[6] -type PI PI
add mapped point datai[5] datai[5] -type PI PI
add mapped point datai[4] datai[4] -type PI PI
add mapped point datai[3] datai[3] -type PI PI
add mapped point datai[2] datai[2] -type PI PI
add mapped point datai[1] datai[1] -type PI PI
add mapped point datai[0] datai[0] -type PI PI

//output ports
add mapped point addr[19] addr[19] -type PO PO
add mapped point addr[18] addr[18] -type PO PO
add mapped point addr[17] addr[17] -type PO PO
add mapped point addr[16] addr[16] -type PO PO
add mapped point addr[15] addr[15] -type PO PO
add mapped point addr[14] addr[14] -type PO PO
add mapped point addr[13] addr[13] -type PO PO
add mapped point addr[12] addr[12] -type PO PO
add mapped point addr[11] addr[11] -type PO PO
add mapped point addr[10] addr[10] -type PO PO
add mapped point addr[9] addr[9] -type PO PO
add mapped point addr[8] addr[8] -type PO PO
add mapped point addr[7] addr[7] -type PO PO
add mapped point addr[6] addr[6] -type PO PO
add mapped point addr[5] addr[5] -type PO PO
add mapped point addr[4] addr[4] -type PO PO
add mapped point addr[3] addr[3] -type PO PO
add mapped point addr[2] addr[2] -type PO PO
add mapped point addr[1] addr[1] -type PO PO
add mapped point addr[0] addr[0] -type PO PO
add mapped point datao[31] datao[31] -type PO PO
add mapped point datao[30] datao[30] -type PO PO
add mapped point datao[29] datao[29] -type PO PO
add mapped point datao[28] datao[28] -type PO PO
add mapped point datao[27] datao[27] -type PO PO
add mapped point datao[26] datao[26] -type PO PO
add mapped point datao[25] datao[25] -type PO PO
add mapped point datao[24] datao[24] -type PO PO
add mapped point datao[23] datao[23] -type PO PO
add mapped point datao[22] datao[22] -type PO PO
add mapped point datao[21] datao[21] -type PO PO
add mapped point datao[20] datao[20] -type PO PO
add mapped point datao[19] datao[19] -type PO PO
add mapped point datao[18] datao[18] -type PO PO
add mapped point datao[17] datao[17] -type PO PO
add mapped point datao[16] datao[16] -type PO PO
add mapped point datao[15] datao[15] -type PO PO
add mapped point datao[14] datao[14] -type PO PO
add mapped point datao[13] datao[13] -type PO PO
add mapped point datao[12] datao[12] -type PO PO
add mapped point datao[11] datao[11] -type PO PO
add mapped point datao[10] datao[10] -type PO PO
add mapped point datao[9] datao[9] -type PO PO
add mapped point datao[8] datao[8] -type PO PO
add mapped point datao[7] datao[7] -type PO PO
add mapped point datao[6] datao[6] -type PO PO
add mapped point datao[5] datao[5] -type PO PO
add mapped point datao[4] datao[4] -type PO PO
add mapped point datao[3] datao[3] -type PO PO
add mapped point datao[2] datao[2] -type PO PO
add mapped point datao[1] datao[1] -type PO PO
add mapped point datao[0] datao[0] -type PO PO
add mapped point rd rd -type PO PO
add mapped point wr wr -type PO PO

//inout ports




//Sequential Pins
add mapped point rd/q rd_reg/Q  -type DFF DFF
add mapped point wr/q wr_reg/Q  -type DFF DFF
add mapped point IR[0]/q IR_reg[0]/Q  -type DFF DFF
add mapped point IR[1]/q IR_reg[1]/Q  -type DFF DFF
add mapped point IR[2]/q IR_reg[2]/Q  -type DFF DFF
add mapped point IR[3]/q IR_reg[3]/Q  -type DFF DFF
add mapped point IR[4]/q IR_reg[4]/Q  -type DFF DFF
add mapped point IR[5]/q IR_reg[5]/Q  -type DFF DFF
add mapped point IR[6]/q IR_reg[6]/Q  -type DFF DFF
add mapped point IR[7]/q IR_reg[7]/Q  -type DFF DFF
add mapped point IR[8]/q IR_reg[8]/Q  -type DFF DFF
add mapped point IR[9]/q IR_reg[9]/Q  -type DFF DFF
add mapped point IR[10]/q IR_reg[10]/Q  -type DFF DFF
add mapped point IR[11]/q IR_reg[11]/Q  -type DFF DFF
add mapped point IR[12]/q IR_reg[12]/Q  -type DFF DFF
add mapped point IR[13]/q IR_reg[13]/Q  -type DFF DFF
add mapped point IR[14]/q IR_reg[14]/Q  -type DFF DFF
add mapped point IR[15]/q IR_reg[15]/Q  -type DFF DFF
add mapped point IR[16]/q IR_reg[16]/Q  -type DFF DFF
add mapped point IR[17]/q IR_reg[17]/Q  -type DFF DFF
add mapped point IR[18]/q IR_reg[18]/Q  -type DFF DFF
add mapped point IR[19]/q IR_reg[19]/Q  -type DFF DFF
add mapped point IR[20]/q IR_reg[20]/Q  -type DFF DFF
add mapped point IR[21]/q IR_reg[21]/Q  -type DFF DFF
add mapped point IR[22]/q IR_reg[22]/Q  -type DFF DFF
add mapped point IR[23]/q IR_reg[23]/Q  -type DFF DFF
add mapped point IR[24]/q IR_reg[24]/Q  -type DFF DFF
add mapped point IR[25]/q IR_reg[25]/Q  -type DFF DFF
add mapped point IR[26]/q IR_reg[26]/Q  -type DFF DFF
add mapped point IR[27]/q IR_reg[27]/Q  -type DFF DFF
add mapped point IR[28]/q IR_reg[28]/Q  -type DFF DFF
add mapped point IR[29]/q IR_reg[29]/Q  -type DFF DFF
add mapped point IR[30]/q IR_reg[30]/Q  -type DFF DFF
add mapped point IR[31]/q IR_reg[31]/Q  -type DFF DFF
add mapped point addr[0]/q addr_reg[0]/Q  -type DFF DFF
add mapped point addr[1]/q addr_reg[1]/Q  -type DFF DFF
add mapped point addr[2]/q addr_reg[2]/Q  -type DFF DFF
add mapped point addr[3]/q addr_reg[3]/Q  -type DFF DFF
add mapped point addr[4]/q addr_reg[4]/Q  -type DFF DFF
add mapped point addr[5]/q addr_reg[5]/Q  -type DFF DFF
add mapped point addr[6]/q addr_reg[6]/Q  -type DFF DFF
add mapped point addr[7]/q addr_reg[7]/Q  -type DFF DFF
add mapped point addr[8]/q addr_reg[8]/Q  -type DFF DFF
add mapped point addr[9]/q addr_reg[9]/Q  -type DFF DFF
add mapped point addr[10]/q addr_reg[10]/Q  -type DFF DFF
add mapped point addr[11]/q addr_reg[11]/Q  -type DFF DFF
add mapped point addr[12]/q addr_reg[12]/Q  -type DFF DFF
add mapped point addr[13]/q addr_reg[13]/Q  -type DFF DFF
add mapped point addr[14]/q addr_reg[14]/Q  -type DFF DFF
add mapped point addr[15]/q addr_reg[15]/Q  -type DFF DFF
add mapped point addr[16]/q addr_reg[16]/Q  -type DFF DFF
add mapped point addr[17]/q addr_reg[17]/Q  -type DFF DFF
add mapped point addr[18]/q addr_reg[18]/Q  -type DFF DFF
add mapped point addr[19]/q addr_reg[19]/Q  -type DFF DFF
add mapped point d[0]/q d_reg[0]/Q  -type DFF DFF
add mapped point d[1]/q d_reg[1]/Q  -type DFF DFF
add mapped point datao[0]/q datao_reg[0]/Q  -type DFF DFF
add mapped point datao[1]/q datao_reg[1]/Q  -type DFF DFF
add mapped point datao[2]/q datao_reg[2]/Q  -type DFF DFF
add mapped point datao[3]/q datao_reg[3]/Q  -type DFF DFF
add mapped point datao[4]/q datao_reg[4]/Q  -type DFF DFF
add mapped point datao[5]/q datao_reg[5]/Q  -type DFF DFF
add mapped point datao[6]/q datao_reg[6]/Q  -type DFF DFF
add mapped point datao[7]/q datao_reg[7]/Q  -type DFF DFF
add mapped point datao[8]/q datao_reg[8]/Q  -type DFF DFF
add mapped point datao[9]/q datao_reg[9]/Q  -type DFF DFF
add mapped point datao[10]/q datao_reg[10]/Q  -type DFF DFF
add mapped point datao[11]/q datao_reg[11]/Q  -type DFF DFF
add mapped point datao[12]/q datao_reg[12]/Q  -type DFF DFF
add mapped point datao[13]/q datao_reg[13]/Q  -type DFF DFF
add mapped point datao[14]/q datao_reg[14]/Q  -type DFF DFF
add mapped point datao[15]/q datao_reg[15]/Q  -type DFF DFF
add mapped point datao[16]/q datao_reg[16]/Q  -type DFF DFF
add mapped point datao[17]/q datao_reg[17]/Q  -type DFF DFF
add mapped point datao[18]/q datao_reg[18]/Q  -type DFF DFF
add mapped point datao[19]/q datao_reg[19]/Q  -type DFF DFF
add mapped point datao[20]/q datao_reg[20]/Q  -type DFF DFF
add mapped point datao[21]/q datao_reg[21]/Q  -type DFF DFF
add mapped point datao[22]/q datao_reg[22]/Q  -type DFF DFF
add mapped point datao[23]/q datao_reg[23]/Q  -type DFF DFF
add mapped point datao[24]/q datao_reg[24]/Q  -type DFF DFF
add mapped point datao[25]/q datao_reg[25]/Q  -type DFF DFF
add mapped point datao[26]/q datao_reg[26]/Q  -type DFF DFF
add mapped point datao[27]/q datao_reg[27]/Q  -type DFF DFF
add mapped point datao[28]/q datao_reg[28]/Q  -type DFF DFF
add mapped point datao[29]/q datao_reg[29]/Q  -type DFF DFF
add mapped point datao[30]/q datao_reg[30]/Q  -type DFF DFF
add mapped point datao[31]/q datao_reg[31]/Q  -type DFF DFF
add mapped point reg0[0]/q reg0_reg[0]/Q  -type DFF DFF
add mapped point reg0[1]/q reg0_reg[1]/Q  -type DFF DFF
add mapped point reg0[2]/q reg0_reg[2]/Q  -type DFF DFF
add mapped point reg0[3]/q reg0_reg[3]/Q  -type DFF DFF
add mapped point reg0[4]/q reg0_reg[4]/Q  -type DFF DFF
add mapped point reg0[5]/q reg0_reg[5]/Q  -type DFF DFF
add mapped point reg0[6]/q reg0_reg[6]/Q  -type DFF DFF
add mapped point reg0[7]/q reg0_reg[7]/Q  -type DFF DFF
add mapped point reg0[8]/q reg0_reg[8]/Q  -type DFF DFF
add mapped point reg0[9]/q reg0_reg[9]/Q  -type DFF DFF
add mapped point reg0[10]/q reg0_reg[10]/Q  -type DFF DFF
add mapped point reg0[11]/q reg0_reg[11]/Q  -type DFF DFF
add mapped point reg0[12]/q reg0_reg[12]/Q  -type DFF DFF
add mapped point reg0[13]/q reg0_reg[13]/Q  -type DFF DFF
add mapped point reg0[14]/q reg0_reg[14]/Q  -type DFF DFF
add mapped point reg0[15]/q reg0_reg[15]/Q  -type DFF DFF
add mapped point reg0[16]/q reg0_reg[16]/Q  -type DFF DFF
add mapped point reg0[17]/q reg0_reg[17]/Q  -type DFF DFF
add mapped point reg0[18]/q reg0_reg[18]/Q  -type DFF DFF
add mapped point reg0[19]/q reg0_reg[19]/Q  -type DFF DFF
add mapped point reg0[20]/q reg0_reg[20]/Q  -type DFF DFF
add mapped point reg0[21]/q reg0_reg[21]/Q  -type DFF DFF
add mapped point reg0[22]/q reg0_reg[22]/Q  -type DFF DFF
add mapped point reg0[23]/q reg0_reg[23]/Q  -type DFF DFF
add mapped point reg0[24]/q reg0_reg[24]/Q  -type DFF DFF
add mapped point reg0[25]/q reg0_reg[25]/Q  -type DFF DFF
add mapped point reg0[26]/q reg0_reg[26]/Q  -type DFF DFF
add mapped point reg0[27]/q reg0_reg[27]/Q  -type DFF DFF
add mapped point reg0[28]/q reg0_reg[28]/Q  -type DFF DFF
add mapped point reg0[29]/q reg0_reg[29]/Q  -type DFF DFF
add mapped point reg0[30]/q reg0_reg[30]/Q  -type DFF DFF
add mapped point reg0[31]/q reg0_reg[31]/Q  -type DFF DFF
add mapped point reg1[0]/q reg1_reg[0]/Q  -type DFF DFF
add mapped point reg1[1]/q reg1_reg[1]/Q  -type DFF DFF
add mapped point reg1[2]/q reg1_reg[2]/Q  -type DFF DFF
add mapped point reg1[3]/q reg1_reg[3]/Q  -type DFF DFF
add mapped point reg1[4]/q reg1_reg[4]/Q  -type DFF DFF
add mapped point reg1[5]/q reg1_reg[5]/Q  -type DFF DFF
add mapped point reg1[6]/q reg1_reg[6]/Q  -type DFF DFF
add mapped point reg1[7]/q reg1_reg[7]/Q  -type DFF DFF
add mapped point reg1[8]/q reg1_reg[8]/Q  -type DFF DFF
add mapped point reg1[9]/q reg1_reg[9]/Q  -type DFF DFF
add mapped point reg1[10]/q reg1_reg[10]/Q  -type DFF DFF
add mapped point reg1[11]/q reg1_reg[11]/Q  -type DFF DFF
add mapped point reg1[12]/q reg1_reg[12]/Q  -type DFF DFF
add mapped point reg1[13]/q reg1_reg[13]/Q  -type DFF DFF
add mapped point reg1[14]/q reg1_reg[14]/Q  -type DFF DFF
add mapped point reg1[15]/q reg1_reg[15]/Q  -type DFF DFF
add mapped point reg1[16]/q reg1_reg[16]/Q  -type DFF DFF
add mapped point reg1[17]/q reg1_reg[17]/Q  -type DFF DFF
add mapped point reg1[18]/q reg1_reg[18]/Q  -type DFF DFF
add mapped point reg1[19]/q reg1_reg[19]/Q  -type DFF DFF
add mapped point reg1[20]/q reg1_reg[20]/Q  -type DFF DFF
add mapped point reg1[21]/q reg1_reg[21]/Q  -type DFF DFF
add mapped point reg1[22]/q reg1_reg[22]/Q  -type DFF DFF
add mapped point reg1[23]/q reg1_reg[23]/Q  -type DFF DFF
add mapped point reg1[24]/q reg1_reg[24]/Q  -type DFF DFF
add mapped point reg1[25]/q reg1_reg[25]/Q  -type DFF DFF
add mapped point reg1[26]/q reg1_reg[26]/Q  -type DFF DFF
add mapped point reg1[27]/q reg1_reg[27]/Q  -type DFF DFF
add mapped point reg1[28]/q reg1_reg[28]/Q  -type DFF DFF
add mapped point reg1[29]/q reg1_reg[29]/Q  -type DFF DFF
add mapped point reg1[30]/q reg1_reg[30]/Q  -type DFF DFF
add mapped point reg1[31]/q reg1_reg[31]/Q  -type DFF DFF
add mapped point reg2[0]/q reg2_reg[0]/Q  -type DFF DFF
add mapped point reg2[1]/q reg2_reg[1]/Q  -type DFF DFF
add mapped point reg2[2]/q reg2_reg[2]/Q  -type DFF DFF
add mapped point reg2[3]/q reg2_reg[3]/Q  -type DFF DFF
add mapped point reg2[4]/q reg2_reg[4]/Q  -type DFF DFF
add mapped point reg2[5]/q reg2_reg[5]/Q  -type DFF DFF
add mapped point reg2[6]/q reg2_reg[6]/Q  -type DFF DFF
add mapped point reg2[7]/q reg2_reg[7]/Q  -type DFF DFF
add mapped point reg2[8]/q reg2_reg[8]/Q  -type DFF DFF
add mapped point reg2[9]/q reg2_reg[9]/Q  -type DFF DFF
add mapped point reg2[10]/q reg2_reg[10]/Q  -type DFF DFF
add mapped point reg2[11]/q reg2_reg[11]/Q  -type DFF DFF
add mapped point reg2[12]/q reg2_reg[12]/Q  -type DFF DFF
add mapped point reg2[13]/q reg2_reg[13]/Q  -type DFF DFF
add mapped point reg2[14]/q reg2_reg[14]/Q  -type DFF DFF
add mapped point reg2[15]/q reg2_reg[15]/Q  -type DFF DFF
add mapped point reg2[16]/q reg2_reg[16]/Q  -type DFF DFF
add mapped point reg2[17]/q reg2_reg[17]/Q  -type DFF DFF
add mapped point reg2[18]/q reg2_reg[18]/Q  -type DFF DFF
add mapped point reg2[19]/q reg2_reg[19]/Q  -type DFF DFF
add mapped point reg2[20]/q reg2_reg[20]/Q  -type DFF DFF
add mapped point reg2[21]/q reg2_reg[21]/Q  -type DFF DFF
add mapped point reg2[22]/q reg2_reg[22]/Q  -type DFF DFF
add mapped point reg2[23]/q reg2_reg[23]/Q  -type DFF DFF
add mapped point reg2[24]/q reg2_reg[24]/Q  -type DFF DFF
add mapped point reg2[25]/q reg2_reg[25]/Q  -type DFF DFF
add mapped point reg2[26]/q reg2_reg[26]/Q  -type DFF DFF
add mapped point reg2[27]/q reg2_reg[27]/Q  -type DFF DFF
add mapped point reg2[28]/q reg2_reg[28]/Q  -type DFF DFF
add mapped point reg2[29]/q reg2_reg[29]/Q  -type DFF DFF
add mapped point reg2[30]/q reg2_reg[30]/Q  -type DFF DFF
add mapped point reg2[31]/q reg2_reg[31]/Q  -type DFF DFF
add mapped point reg3[1]/q reg3_reg[1]/Q  -type DFF DFF
add mapped point reg3[2]/q reg3_reg[2]/Q  -type DFF DFF
add mapped point reg3[3]/q reg3_reg[3]/Q  -type DFF DFF
add mapped point reg3[4]/q reg3_reg[4]/Q  -type DFF DFF
add mapped point reg3[5]/q reg3_reg[5]/Q  -type DFF DFF
add mapped point reg3[6]/q reg3_reg[6]/Q  -type DFF DFF
add mapped point reg3[7]/q reg3_reg[7]/Q  -type DFF DFF
add mapped point reg3[8]/q reg3_reg[8]/Q  -type DFF DFF
add mapped point reg3[9]/q reg3_reg[9]/Q  -type DFF DFF
add mapped point reg3[10]/q reg3_reg[10]/Q  -type DFF DFF
add mapped point reg3[11]/q reg3_reg[11]/Q  -type DFF DFF
add mapped point reg3[12]/q reg3_reg[12]/Q  -type DFF DFF
add mapped point reg3[13]/q reg3_reg[13]/Q  -type DFF DFF
add mapped point reg3[14]/q reg3_reg[14]/Q  -type DFF DFF
add mapped point reg3[15]/q reg3_reg[15]/Q  -type DFF DFF
add mapped point reg3[16]/q reg3_reg[16]/Q  -type DFF DFF
add mapped point reg3[17]/q reg3_reg[17]/Q  -type DFF DFF
add mapped point reg3[18]/q reg3_reg[18]/Q  -type DFF DFF
add mapped point reg3[19]/q reg3_reg[19]/Q  -type DFF DFF
add mapped point reg3[20]/q reg3_reg[20]/Q  -type DFF DFF
add mapped point reg3[21]/q reg3_reg[21]/Q  -type DFF DFF
add mapped point reg3[22]/q reg3_reg[22]/Q  -type DFF DFF
add mapped point reg3[23]/q reg3_reg[23]/Q  -type DFF DFF
add mapped point reg3[24]/q reg3_reg[24]/Q  -type DFF DFF
add mapped point reg3[25]/q reg3_reg[25]/Q  -type DFF DFF
add mapped point reg3[26]/q reg3_reg[26]/Q  -type DFF DFF
add mapped point reg3[27]/q reg3_reg[27]/Q  -type DFF DFF
add mapped point reg3[28]/q reg3_reg[28]/Q  -type DFF DFF
add mapped point B/q B_reg/Q  -type DFF DFF
add mapped point B/q B_reg/QN  -type DFF DFF
add mapped point reg3[0]/q reg3_reg[0]/Q  -type DFF DFF
add mapped point reg3[0]/q reg3_reg[0]/QN  -type DFF DFF
add mapped point state/q state_reg/Q  -type DFF DFF
add mapped point state/q state_reg/QN  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
