
//input ports
add mapped point i_mode i_mode -type PI PI
add mapped point i_clk i_clk -type PI PI
add mapped point i_en i_en -type PI PI
add mapped point i_clr i_clr -type PI PI
add mapped point i_A[63] i_A[63] -type PI PI
add mapped point i_A[62] i_A[62] -type PI PI
add mapped point i_A[61] i_A[61] -type PI PI
add mapped point i_A[60] i_A[60] -type PI PI
add mapped point i_A[59] i_A[59] -type PI PI
add mapped point i_A[58] i_A[58] -type PI PI
add mapped point i_A[57] i_A[57] -type PI PI
add mapped point i_A[56] i_A[56] -type PI PI
add mapped point i_A[55] i_A[55] -type PI PI
add mapped point i_A[54] i_A[54] -type PI PI
add mapped point i_A[53] i_A[53] -type PI PI
add mapped point i_A[52] i_A[52] -type PI PI
add mapped point i_A[51] i_A[51] -type PI PI
add mapped point i_A[50] i_A[50] -type PI PI
add mapped point i_A[49] i_A[49] -type PI PI
add mapped point i_A[48] i_A[48] -type PI PI
add mapped point i_A[47] i_A[47] -type PI PI
add mapped point i_A[46] i_A[46] -type PI PI
add mapped point i_A[45] i_A[45] -type PI PI
add mapped point i_A[44] i_A[44] -type PI PI
add mapped point i_A[43] i_A[43] -type PI PI
add mapped point i_A[42] i_A[42] -type PI PI
add mapped point i_A[41] i_A[41] -type PI PI
add mapped point i_A[40] i_A[40] -type PI PI
add mapped point i_A[39] i_A[39] -type PI PI
add mapped point i_A[38] i_A[38] -type PI PI
add mapped point i_A[37] i_A[37] -type PI PI
add mapped point i_A[36] i_A[36] -type PI PI
add mapped point i_A[35] i_A[35] -type PI PI
add mapped point i_A[34] i_A[34] -type PI PI
add mapped point i_A[33] i_A[33] -type PI PI
add mapped point i_A[32] i_A[32] -type PI PI
add mapped point i_A[31] i_A[31] -type PI PI
add mapped point i_A[30] i_A[30] -type PI PI
add mapped point i_A[29] i_A[29] -type PI PI
add mapped point i_A[28] i_A[28] -type PI PI
add mapped point i_A[27] i_A[27] -type PI PI
add mapped point i_A[26] i_A[26] -type PI PI
add mapped point i_A[25] i_A[25] -type PI PI
add mapped point i_A[24] i_A[24] -type PI PI
add mapped point i_A[23] i_A[23] -type PI PI
add mapped point i_A[22] i_A[22] -type PI PI
add mapped point i_A[21] i_A[21] -type PI PI
add mapped point i_A[20] i_A[20] -type PI PI
add mapped point i_A[19] i_A[19] -type PI PI
add mapped point i_A[18] i_A[18] -type PI PI
add mapped point i_A[17] i_A[17] -type PI PI
add mapped point i_A[16] i_A[16] -type PI PI
add mapped point i_A[15] i_A[15] -type PI PI
add mapped point i_A[14] i_A[14] -type PI PI
add mapped point i_A[13] i_A[13] -type PI PI
add mapped point i_A[12] i_A[12] -type PI PI
add mapped point i_A[11] i_A[11] -type PI PI
add mapped point i_A[10] i_A[10] -type PI PI
add mapped point i_A[9] i_A[9] -type PI PI
add mapped point i_A[8] i_A[8] -type PI PI
add mapped point i_A[7] i_A[7] -type PI PI
add mapped point i_A[6] i_A[6] -type PI PI
add mapped point i_A[5] i_A[5] -type PI PI
add mapped point i_A[4] i_A[4] -type PI PI
add mapped point i_A[3] i_A[3] -type PI PI
add mapped point i_A[2] i_A[2] -type PI PI
add mapped point i_A[1] i_A[1] -type PI PI
add mapped point i_A[0] i_A[0] -type PI PI
add mapped point i_B[63] i_B[63] -type PI PI
add mapped point i_B[62] i_B[62] -type PI PI
add mapped point i_B[61] i_B[61] -type PI PI
add mapped point i_B[60] i_B[60] -type PI PI
add mapped point i_B[59] i_B[59] -type PI PI
add mapped point i_B[58] i_B[58] -type PI PI
add mapped point i_B[57] i_B[57] -type PI PI
add mapped point i_B[56] i_B[56] -type PI PI
add mapped point i_B[55] i_B[55] -type PI PI
add mapped point i_B[54] i_B[54] -type PI PI
add mapped point i_B[53] i_B[53] -type PI PI
add mapped point i_B[52] i_B[52] -type PI PI
add mapped point i_B[51] i_B[51] -type PI PI
add mapped point i_B[50] i_B[50] -type PI PI
add mapped point i_B[49] i_B[49] -type PI PI
add mapped point i_B[48] i_B[48] -type PI PI
add mapped point i_B[47] i_B[47] -type PI PI
add mapped point i_B[46] i_B[46] -type PI PI
add mapped point i_B[45] i_B[45] -type PI PI
add mapped point i_B[44] i_B[44] -type PI PI
add mapped point i_B[43] i_B[43] -type PI PI
add mapped point i_B[42] i_B[42] -type PI PI
add mapped point i_B[41] i_B[41] -type PI PI
add mapped point i_B[40] i_B[40] -type PI PI
add mapped point i_B[39] i_B[39] -type PI PI
add mapped point i_B[38] i_B[38] -type PI PI
add mapped point i_B[37] i_B[37] -type PI PI
add mapped point i_B[36] i_B[36] -type PI PI
add mapped point i_B[35] i_B[35] -type PI PI
add mapped point i_B[34] i_B[34] -type PI PI
add mapped point i_B[33] i_B[33] -type PI PI
add mapped point i_B[32] i_B[32] -type PI PI
add mapped point i_B[31] i_B[31] -type PI PI
add mapped point i_B[30] i_B[30] -type PI PI
add mapped point i_B[29] i_B[29] -type PI PI
add mapped point i_B[28] i_B[28] -type PI PI
add mapped point i_B[27] i_B[27] -type PI PI
add mapped point i_B[26] i_B[26] -type PI PI
add mapped point i_B[25] i_B[25] -type PI PI
add mapped point i_B[24] i_B[24] -type PI PI
add mapped point i_B[23] i_B[23] -type PI PI
add mapped point i_B[22] i_B[22] -type PI PI
add mapped point i_B[21] i_B[21] -type PI PI
add mapped point i_B[20] i_B[20] -type PI PI
add mapped point i_B[19] i_B[19] -type PI PI
add mapped point i_B[18] i_B[18] -type PI PI
add mapped point i_B[17] i_B[17] -type PI PI
add mapped point i_B[16] i_B[16] -type PI PI
add mapped point i_B[15] i_B[15] -type PI PI
add mapped point i_B[14] i_B[14] -type PI PI
add mapped point i_B[13] i_B[13] -type PI PI
add mapped point i_B[12] i_B[12] -type PI PI
add mapped point i_B[11] i_B[11] -type PI PI
add mapped point i_B[10] i_B[10] -type PI PI
add mapped point i_B[9] i_B[9] -type PI PI
add mapped point i_B[8] i_B[8] -type PI PI
add mapped point i_B[7] i_B[7] -type PI PI
add mapped point i_B[6] i_B[6] -type PI PI
add mapped point i_B[5] i_B[5] -type PI PI
add mapped point i_B[4] i_B[4] -type PI PI
add mapped point i_B[3] i_B[3] -type PI PI
add mapped point i_B[2] i_B[2] -type PI PI
add mapped point i_B[1] i_B[1] -type PI PI
add mapped point i_B[0] i_B[0] -type PI PI

//output ports
add mapped point o_res[63] o_res[63] -type PO PO
add mapped point o_res[62] o_res[62] -type PO PO
add mapped point o_res[61] o_res[61] -type PO PO
add mapped point o_res[60] o_res[60] -type PO PO
add mapped point o_res[59] o_res[59] -type PO PO
add mapped point o_res[58] o_res[58] -type PO PO
add mapped point o_res[57] o_res[57] -type PO PO
add mapped point o_res[56] o_res[56] -type PO PO
add mapped point o_res[55] o_res[55] -type PO PO
add mapped point o_res[54] o_res[54] -type PO PO
add mapped point o_res[53] o_res[53] -type PO PO
add mapped point o_res[52] o_res[52] -type PO PO
add mapped point o_res[51] o_res[51] -type PO PO
add mapped point o_res[50] o_res[50] -type PO PO
add mapped point o_res[49] o_res[49] -type PO PO
add mapped point o_res[48] o_res[48] -type PO PO
add mapped point o_res[47] o_res[47] -type PO PO
add mapped point o_res[46] o_res[46] -type PO PO
add mapped point o_res[45] o_res[45] -type PO PO
add mapped point o_res[44] o_res[44] -type PO PO
add mapped point o_res[43] o_res[43] -type PO PO
add mapped point o_res[42] o_res[42] -type PO PO
add mapped point o_res[41] o_res[41] -type PO PO
add mapped point o_res[40] o_res[40] -type PO PO
add mapped point o_res[39] o_res[39] -type PO PO
add mapped point o_res[38] o_res[38] -type PO PO
add mapped point o_res[37] o_res[37] -type PO PO
add mapped point o_res[36] o_res[36] -type PO PO
add mapped point o_res[35] o_res[35] -type PO PO
add mapped point o_res[34] o_res[34] -type PO PO
add mapped point o_res[33] o_res[33] -type PO PO
add mapped point o_res[32] o_res[32] -type PO PO
add mapped point o_res[31] o_res[31] -type PO PO
add mapped point o_res[30] o_res[30] -type PO PO
add mapped point o_res[29] o_res[29] -type PO PO
add mapped point o_res[28] o_res[28] -type PO PO
add mapped point o_res[27] o_res[27] -type PO PO
add mapped point o_res[26] o_res[26] -type PO PO
add mapped point o_res[25] o_res[25] -type PO PO
add mapped point o_res[24] o_res[24] -type PO PO
add mapped point o_res[23] o_res[23] -type PO PO
add mapped point o_res[22] o_res[22] -type PO PO
add mapped point o_res[21] o_res[21] -type PO PO
add mapped point o_res[20] o_res[20] -type PO PO
add mapped point o_res[19] o_res[19] -type PO PO
add mapped point o_res[18] o_res[18] -type PO PO
add mapped point o_res[17] o_res[17] -type PO PO
add mapped point o_res[16] o_res[16] -type PO PO
add mapped point o_res[15] o_res[15] -type PO PO
add mapped point o_res[14] o_res[14] -type PO PO
add mapped point o_res[13] o_res[13] -type PO PO
add mapped point o_res[12] o_res[12] -type PO PO
add mapped point o_res[11] o_res[11] -type PO PO
add mapped point o_res[10] o_res[10] -type PO PO
add mapped point o_res[9] o_res[9] -type PO PO
add mapped point o_res[8] o_res[8] -type PO PO
add mapped point o_res[7] o_res[7] -type PO PO
add mapped point o_res[6] o_res[6] -type PO PO
add mapped point o_res[5] o_res[5] -type PO PO
add mapped point o_res[4] o_res[4] -type PO PO
add mapped point o_res[3] o_res[3] -type PO PO
add mapped point o_res[2] o_res[2] -type PO PO
add mapped point o_res[1] o_res[1] -type PO PO
add mapped point o_res[0] o_res[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point p0/a_Ls[0]/q p0/a_Ls_reg[0]/Q  -type DFF DFF
add mapped point p0/a_Ls[1]/q p0/a_Ls_reg[1]/Q  -type DFF DFF
add mapped point p0/a_large_exp[0]/q p0/a_large_exp_reg[0]/Q  -type DFF DFF
add mapped point p0/a_large_exp[1]/q p0/a_large_exp_reg[1]/Q  -type DFF DFF
add mapped point p0/a_large_exp[2]/q p0/a_large_exp_reg[2]/Q  -type DFF DFF
add mapped point p0/a_large_exp[3]/q p0/a_large_exp_reg[3]/Q  -type DFF DFF
add mapped point p0/a_large_exp[4]/q p0/a_large_exp_reg[4]/Q  -type DFF DFF
add mapped point p0/a_large_exp[5]/q p0/a_large_exp_reg[5]/Q  -type DFF DFF
add mapped point p0/a_large_exp[6]/q p0/a_large_exp_reg[6]/Q  -type DFF DFF
add mapped point p0/a_large_exp[7]/q p0/a_large_exp_reg[7]/Q  -type DFF DFF
add mapped point p0/a_large_exp[8]/q p0/a_large_exp_reg[8]/Q  -type DFF DFF
add mapped point p0/a_large_exp[9]/q p0/a_large_exp_reg[9]/Q  -type DFF DFF
add mapped point p0/a_large_exp[10]/q p0/a_large_exp_reg[10]/Q  -type DFF DFF
add mapped point p0/a_large_exp[11]/q p0/a_large_exp_reg[11]/Q  -type DFF DFF
add mapped point p0/a_large_exp[12]/q p0/a_large_exp_reg[12]/Q  -type DFF DFF
add mapped point p0/a_large_exp[13]/q p0/a_large_exp_reg[13]/Q  -type DFF DFF
add mapped point p0/a_large_exp[14]/q p0/a_large_exp_reg[14]/Q  -type DFF DFF
add mapped point p0/a_large_exp[15]/q p0/a_large_exp_reg[15]/Q  -type DFF DFF
add mapped point p0/a_large_expff[0]/q p0/a_large_expff_reg[0]/Q  -type DFF DFF
add mapped point p0/a_large_expff[1]/q p0/a_large_expff_reg[1]/Q  -type DFF DFF
add mapped point p0/a_large_frac00[0]/q p0/a_large_frac00_reg[0]/Q  -type DFF DFF
add mapped point p0/a_large_frac00[1]/q p0/a_large_frac00_reg[1]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[0]/q p0/a_large_frac53_reg[0]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[1]/q p0/a_large_frac53_reg[1]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[2]/q p0/a_large_frac53_reg[2]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[3]/q p0/a_large_frac53_reg[3]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[4]/q p0/a_large_frac53_reg[4]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[5]/q p0/a_large_frac53_reg[5]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[6]/q p0/a_large_frac53_reg[6]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[7]/q p0/a_large_frac53_reg[7]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[8]/q p0/a_large_frac53_reg[8]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[9]/q p0/a_large_frac53_reg[9]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[10]/q p0/a_large_frac53_reg[10]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[11]/q p0/a_large_frac53_reg[11]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[12]/q p0/a_large_frac53_reg[12]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[13]/q p0/a_large_frac53_reg[13]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[14]/q p0/a_large_frac53_reg[14]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[15]/q p0/a_large_frac53_reg[15]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[16]/q p0/a_large_frac53_reg[16]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[17]/q p0/a_large_frac53_reg[17]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[18]/q p0/a_large_frac53_reg[18]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[19]/q p0/a_large_frac53_reg[19]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[20]/q p0/a_large_frac53_reg[20]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[21]/q p0/a_large_frac53_reg[21]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[22]/q p0/a_large_frac53_reg[22]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[23]/q p0/a_large_frac53_reg[23]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[24]/q p0/a_large_frac53_reg[24]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[25]/q p0/a_large_frac53_reg[25]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[26]/q p0/a_large_frac53_reg[26]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[27]/q p0/a_large_frac53_reg[27]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[28]/q p0/a_large_frac53_reg[28]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[29]/q p0/a_large_frac53_reg[29]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[30]/q p0/a_large_frac53_reg[30]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[31]/q p0/a_large_frac53_reg[31]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[32]/q p0/a_large_frac53_reg[32]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[33]/q p0/a_large_frac53_reg[33]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[34]/q p0/a_large_frac53_reg[34]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[35]/q p0/a_large_frac53_reg[35]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[36]/q p0/a_large_frac53_reg[36]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[37]/q p0/a_large_frac53_reg[37]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[38]/q p0/a_large_frac53_reg[38]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[39]/q p0/a_large_frac53_reg[39]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[40]/q p0/a_large_frac53_reg[40]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[41]/q p0/a_large_frac53_reg[41]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[42]/q p0/a_large_frac53_reg[42]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[43]/q p0/a_large_frac53_reg[43]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[44]/q p0/a_large_frac53_reg[44]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[45]/q p0/a_large_frac53_reg[45]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[46]/q p0/a_large_frac53_reg[46]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[47]/q p0/a_large_frac53_reg[47]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[48]/q p0/a_large_frac53_reg[48]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[49]/q p0/a_large_frac53_reg[49]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[50]/q p0/a_large_frac53_reg[50]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[51]/q p0/a_large_frac53_reg[51]/Q  -type DFF DFF
add mapped point p0/a_large_frac53[52]/q p0/a_large_frac53_reg[52]/Q  -type DFF DFF
add mapped point p0/a_large_hidden_bit[0]/q p0/a_large_hidden_bit_reg[0]/Q  -type DFF DFF
add mapped point p0/a_mode/q p0/a_mode_reg/Q  -type DFF DFF
add mapped point p0/a_op[0]/q p0/a_op_reg[0]/Q  -type DFF DFF
add mapped point p0/a_op[1]/q p0/a_op_reg[1]/Q  -type DFF DFF
add mapped point p0/a_small_exp[0]/q p0/a_small_exp_reg[0]/Q  -type DFF DFF
add mapped point p0/a_small_exp[1]/q p0/a_small_exp_reg[1]/Q  -type DFF DFF
add mapped point p0/a_small_exp[2]/q p0/a_small_exp_reg[2]/Q  -type DFF DFF
add mapped point p0/a_small_exp[3]/q p0/a_small_exp_reg[3]/Q  -type DFF DFF
add mapped point p0/a_small_exp[4]/q p0/a_small_exp_reg[4]/Q  -type DFF DFF
add mapped point p0/a_small_exp[5]/q p0/a_small_exp_reg[5]/Q  -type DFF DFF
add mapped point p0/a_small_exp[6]/q p0/a_small_exp_reg[6]/Q  -type DFF DFF
add mapped point p0/a_small_exp[7]/q p0/a_small_exp_reg[7]/Q  -type DFF DFF
add mapped point p0/a_small_exp[8]/q p0/a_small_exp_reg[8]/Q  -type DFF DFF
add mapped point p0/a_small_exp[9]/q p0/a_small_exp_reg[9]/Q  -type DFF DFF
add mapped point p0/a_small_exp[10]/q p0/a_small_exp_reg[10]/Q  -type DFF DFF
add mapped point p0/a_small_exp[11]/q p0/a_small_exp_reg[11]/Q  -type DFF DFF
add mapped point p0/a_small_exp[12]/q p0/a_small_exp_reg[12]/Q  -type DFF DFF
add mapped point p0/a_small_exp[13]/q p0/a_small_exp_reg[13]/Q  -type DFF DFF
add mapped point p0/a_small_exp[14]/q p0/a_small_exp_reg[14]/Q  -type DFF DFF
add mapped point p0/a_small_exp[15]/q p0/a_small_exp_reg[15]/Q  -type DFF DFF
add mapped point p0/a_small_expff[0]/q p0/a_small_expff_reg[0]/Q  -type DFF DFF
add mapped point p0/a_small_expff[1]/q p0/a_small_expff_reg[1]/Q  -type DFF DFF
add mapped point p0/a_small_frac00[0]/q p0/a_small_frac00_reg[0]/Q  -type DFF DFF
add mapped point p0/a_small_frac00[1]/q p0/a_small_frac00_reg[1]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[0]/q p0/a_small_frac53_reg[0]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[1]/q p0/a_small_frac53_reg[1]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[2]/q p0/a_small_frac53_reg[2]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[3]/q p0/a_small_frac53_reg[3]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[4]/q p0/a_small_frac53_reg[4]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[5]/q p0/a_small_frac53_reg[5]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[6]/q p0/a_small_frac53_reg[6]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[7]/q p0/a_small_frac53_reg[7]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[8]/q p0/a_small_frac53_reg[8]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[9]/q p0/a_small_frac53_reg[9]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[10]/q p0/a_small_frac53_reg[10]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[11]/q p0/a_small_frac53_reg[11]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[12]/q p0/a_small_frac53_reg[12]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[13]/q p0/a_small_frac53_reg[13]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[14]/q p0/a_small_frac53_reg[14]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[15]/q p0/a_small_frac53_reg[15]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[16]/q p0/a_small_frac53_reg[16]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[17]/q p0/a_small_frac53_reg[17]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[18]/q p0/a_small_frac53_reg[18]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[19]/q p0/a_small_frac53_reg[19]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[20]/q p0/a_small_frac53_reg[20]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[21]/q p0/a_small_frac53_reg[21]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[22]/q p0/a_small_frac53_reg[22]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[23]/q p0/a_small_frac53_reg[23]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[24]/q p0/a_small_frac53_reg[24]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[25]/q p0/a_small_frac53_reg[25]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[26]/q p0/a_small_frac53_reg[26]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[27]/q p0/a_small_frac53_reg[27]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[28]/q p0/a_small_frac53_reg[28]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[29]/q p0/a_small_frac53_reg[29]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[30]/q p0/a_small_frac53_reg[30]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[31]/q p0/a_small_frac53_reg[31]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[32]/q p0/a_small_frac53_reg[32]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[33]/q p0/a_small_frac53_reg[33]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[34]/q p0/a_small_frac53_reg[34]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[35]/q p0/a_small_frac53_reg[35]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[36]/q p0/a_small_frac53_reg[36]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[37]/q p0/a_small_frac53_reg[37]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[38]/q p0/a_small_frac53_reg[38]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[39]/q p0/a_small_frac53_reg[39]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[40]/q p0/a_small_frac53_reg[40]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[41]/q p0/a_small_frac53_reg[41]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[42]/q p0/a_small_frac53_reg[42]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[43]/q p0/a_small_frac53_reg[43]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[44]/q p0/a_small_frac53_reg[44]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[45]/q p0/a_small_frac53_reg[45]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[46]/q p0/a_small_frac53_reg[46]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[47]/q p0/a_small_frac53_reg[47]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[48]/q p0/a_small_frac53_reg[48]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[49]/q p0/a_small_frac53_reg[49]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[50]/q p0/a_small_frac53_reg[50]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[51]/q p0/a_small_frac53_reg[51]/Q  -type DFF DFF
add mapped point p0/a_small_frac53[52]/q p0/a_small_frac53_reg[52]/Q  -type DFF DFF
add mapped point p0/a_small_hidden_bit[0]/q p0/a_small_hidden_bit_reg[0]/Q  -type DFF DFF
add mapped point p1/o_Ls[0]/q p1/o_Ls_reg[0]/Q  -type DFF DFF
add mapped point p1/o_Ls[1]/q p1/o_Ls_reg[1]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[0]/q p1/o_aligned_large_frac54_reg[0]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[1]/q p1/o_aligned_large_frac54_reg[1]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[2]/q p1/o_aligned_large_frac54_reg[2]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[3]/q p1/o_aligned_large_frac54_reg[3]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[4]/q p1/o_aligned_large_frac54_reg[4]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[5]/q p1/o_aligned_large_frac54_reg[5]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[6]/q p1/o_aligned_large_frac54_reg[6]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[7]/q p1/o_aligned_large_frac54_reg[7]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[8]/q p1/o_aligned_large_frac54_reg[8]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[9]/q p1/o_aligned_large_frac54_reg[9]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[10]/q p1/o_aligned_large_frac54_reg[10]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[11]/q p1/o_aligned_large_frac54_reg[11]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[12]/q p1/o_aligned_large_frac54_reg[12]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[13]/q p1/o_aligned_large_frac54_reg[13]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[14]/q p1/o_aligned_large_frac54_reg[14]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[15]/q p1/o_aligned_large_frac54_reg[15]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[16]/q p1/o_aligned_large_frac54_reg[16]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[17]/q p1/o_aligned_large_frac54_reg[17]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[18]/q p1/o_aligned_large_frac54_reg[18]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[19]/q p1/o_aligned_large_frac54_reg[19]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[20]/q p1/o_aligned_large_frac54_reg[20]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[21]/q p1/o_aligned_large_frac54_reg[21]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[22]/q p1/o_aligned_large_frac54_reg[22]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[23]/q p1/o_aligned_large_frac54_reg[23]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[24]/q p1/o_aligned_large_frac54_reg[24]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[25]/q p1/o_aligned_large_frac54_reg[25]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[26]/q p1/o_aligned_large_frac54_reg[26]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[27]/q p1/o_aligned_large_frac54_reg[27]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[28]/q p1/o_aligned_large_frac54_reg[28]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[29]/q p1/o_aligned_large_frac54_reg[29]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[30]/q p1/o_aligned_large_frac54_reg[30]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[31]/q p1/o_aligned_large_frac54_reg[31]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[32]/q p1/o_aligned_large_frac54_reg[32]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[33]/q p1/o_aligned_large_frac54_reg[33]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[34]/q p1/o_aligned_large_frac54_reg[34]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[35]/q p1/o_aligned_large_frac54_reg[35]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[36]/q p1/o_aligned_large_frac54_reg[36]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[37]/q p1/o_aligned_large_frac54_reg[37]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[38]/q p1/o_aligned_large_frac54_reg[38]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[39]/q p1/o_aligned_large_frac54_reg[39]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[40]/q p1/o_aligned_large_frac54_reg[40]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[41]/q p1/o_aligned_large_frac54_reg[41]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[42]/q p1/o_aligned_large_frac54_reg[42]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[43]/q p1/o_aligned_large_frac54_reg[43]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[44]/q p1/o_aligned_large_frac54_reg[44]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[45]/q p1/o_aligned_large_frac54_reg[45]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[46]/q p1/o_aligned_large_frac54_reg[46]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[47]/q p1/o_aligned_large_frac54_reg[47]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[48]/q p1/o_aligned_large_frac54_reg[48]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[49]/q p1/o_aligned_large_frac54_reg[49]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[50]/q p1/o_aligned_large_frac54_reg[50]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[51]/q p1/o_aligned_large_frac54_reg[51]/Q  -type DFF DFF
add mapped point p1/o_aligned_large_frac54[52]/q p1/o_aligned_large_frac54_reg[52]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[0]/q p1/o_aligned_small_frac54_reg[0]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[1]/q p1/o_aligned_small_frac54_reg[1]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[2]/q p1/o_aligned_small_frac54_reg[2]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[3]/q p1/o_aligned_small_frac54_reg[3]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[4]/q p1/o_aligned_small_frac54_reg[4]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[5]/q p1/o_aligned_small_frac54_reg[5]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[6]/q p1/o_aligned_small_frac54_reg[6]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[7]/q p1/o_aligned_small_frac54_reg[7]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[8]/q p1/o_aligned_small_frac54_reg[8]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[9]/q p1/o_aligned_small_frac54_reg[9]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[10]/q p1/o_aligned_small_frac54_reg[10]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[11]/q p1/o_aligned_small_frac54_reg[11]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[12]/q p1/o_aligned_small_frac54_reg[12]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[13]/q p1/o_aligned_small_frac54_reg[13]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[14]/q p1/o_aligned_small_frac54_reg[14]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[15]/q p1/o_aligned_small_frac54_reg[15]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[16]/q p1/o_aligned_small_frac54_reg[16]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[17]/q p1/o_aligned_small_frac54_reg[17]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[18]/q p1/o_aligned_small_frac54_reg[18]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[19]/q p1/o_aligned_small_frac54_reg[19]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[20]/q p1/o_aligned_small_frac54_reg[20]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[21]/q p1/o_aligned_small_frac54_reg[21]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[22]/q p1/o_aligned_small_frac54_reg[22]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[23]/q p1/o_aligned_small_frac54_reg[23]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[24]/q p1/o_aligned_small_frac54_reg[24]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[25]/q p1/o_aligned_small_frac54_reg[25]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[26]/q p1/o_aligned_small_frac54_reg[26]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[27]/q p1/o_aligned_small_frac54_reg[27]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[28]/q p1/o_aligned_small_frac54_reg[28]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[29]/q p1/o_aligned_small_frac54_reg[29]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[30]/q p1/o_aligned_small_frac54_reg[30]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[31]/q p1/o_aligned_small_frac54_reg[31]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[32]/q p1/o_aligned_small_frac54_reg[32]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[33]/q p1/o_aligned_small_frac54_reg[33]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[34]/q p1/o_aligned_small_frac54_reg[34]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[35]/q p1/o_aligned_small_frac54_reg[35]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[36]/q p1/o_aligned_small_frac54_reg[36]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[37]/q p1/o_aligned_small_frac54_reg[37]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[38]/q p1/o_aligned_small_frac54_reg[38]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[39]/q p1/o_aligned_small_frac54_reg[39]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[40]/q p1/o_aligned_small_frac54_reg[40]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[41]/q p1/o_aligned_small_frac54_reg[41]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[42]/q p1/o_aligned_small_frac54_reg[42]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[43]/q p1/o_aligned_small_frac54_reg[43]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[44]/q p1/o_aligned_small_frac54_reg[44]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[45]/q p1/o_aligned_small_frac54_reg[45]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[46]/q p1/o_aligned_small_frac54_reg[46]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[47]/q p1/o_aligned_small_frac54_reg[47]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[48]/q p1/o_aligned_small_frac54_reg[48]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[49]/q p1/o_aligned_small_frac54_reg[49]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[50]/q p1/o_aligned_small_frac54_reg[50]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[51]/q p1/o_aligned_small_frac54_reg[51]/Q  -type DFF DFF
add mapped point p1/o_aligned_small_frac54[52]/q p1/o_aligned_small_frac54_reg[52]/Q  -type DFF DFF
add mapped point p1/o_large_exp[0]/q p1/o_large_exp_reg[0]/Q  -type DFF DFF
add mapped point p1/o_large_exp[1]/q p1/o_large_exp_reg[1]/Q  -type DFF DFF
add mapped point p1/o_large_exp[2]/q p1/o_large_exp_reg[2]/Q  -type DFF DFF
add mapped point p1/o_large_exp[3]/q p1/o_large_exp_reg[3]/Q  -type DFF DFF
add mapped point p1/o_large_exp[4]/q p1/o_large_exp_reg[4]/Q  -type DFF DFF
add mapped point p1/o_large_exp[5]/q p1/o_large_exp_reg[5]/Q  -type DFF DFF
add mapped point p1/o_large_exp[6]/q p1/o_large_exp_reg[6]/Q  -type DFF DFF
add mapped point p1/o_large_exp[7]/q p1/o_large_exp_reg[7]/Q  -type DFF DFF
add mapped point p1/o_large_exp[8]/q p1/o_large_exp_reg[8]/Q  -type DFF DFF
add mapped point p1/o_large_exp[9]/q p1/o_large_exp_reg[9]/Q  -type DFF DFF
add mapped point p1/o_large_exp[10]/q p1/o_large_exp_reg[10]/Q  -type DFF DFF
add mapped point p1/o_large_exp[11]/q p1/o_large_exp_reg[11]/Q  -type DFF DFF
add mapped point p1/o_large_exp[12]/q p1/o_large_exp_reg[12]/Q  -type DFF DFF
add mapped point p1/o_large_exp[13]/q p1/o_large_exp_reg[13]/Q  -type DFF DFF
add mapped point p1/o_large_exp[14]/q p1/o_large_exp_reg[14]/Q  -type DFF DFF
add mapped point p1/o_large_exp[15]/q p1/o_large_exp_reg[15]/Q  -type DFF DFF
add mapped point p1/o_large_expff[0]/q p1/o_large_expff_reg[0]/Q  -type DFF DFF
add mapped point p1/o_large_expff[1]/q p1/o_large_expff_reg[1]/Q  -type DFF DFF
add mapped point p1/o_large_frac00[0]/q p1/o_large_frac00_reg[0]/Q  -type DFF DFF
add mapped point p1/o_large_frac00[1]/q p1/o_large_frac00_reg[1]/Q  -type DFF DFF
add mapped point p1/o_mode/q p1/o_mode_reg/Q  -type DFF DFF
add mapped point p1/o_op[0]/q p1/o_op_reg[0]/Q  -type DFF DFF
add mapped point p1/o_op[1]/q p1/o_op_reg[1]/Q  -type DFF DFF
add mapped point p1/o_small_expff[0]/q p1/o_small_expff_reg[0]/Q  -type DFF DFF
add mapped point p1/o_small_expff[1]/q p1/o_small_expff_reg[1]/Q  -type DFF DFF
add mapped point p1/o_small_frac00[0]/q p1/o_small_frac00_reg[0]/Q  -type DFF DFF
add mapped point p1/o_small_frac00[1]/q p1/o_small_frac00_reg[1]/Q  -type DFF DFF
add mapped point p2/n_Ls[0]/q p2/n_Ls_reg[0]/Q  -type DFF DFF
add mapped point p2/n_Ls[1]/q p2/n_Ls_reg[1]/Q  -type DFF DFF
add mapped point p2/n_exp[0]/q p2/n_exp_reg[0]/Q  -type DFF DFF
add mapped point p2/n_exp[1]/q p2/n_exp_reg[1]/Q  -type DFF DFF
add mapped point p2/n_exp[2]/q p2/n_exp_reg[2]/Q  -type DFF DFF
add mapped point p2/n_exp[3]/q p2/n_exp_reg[3]/Q  -type DFF DFF
add mapped point p2/n_exp[4]/q p2/n_exp_reg[4]/Q  -type DFF DFF
add mapped point p2/n_exp[5]/q p2/n_exp_reg[5]/Q  -type DFF DFF
add mapped point p2/n_exp[6]/q p2/n_exp_reg[6]/Q  -type DFF DFF
add mapped point p2/n_exp[7]/q p2/n_exp_reg[7]/Q  -type DFF DFF
add mapped point p2/n_exp[8]/q p2/n_exp_reg[8]/Q  -type DFF DFF
add mapped point p2/n_exp[9]/q p2/n_exp_reg[9]/Q  -type DFF DFF
add mapped point p2/n_exp[10]/q p2/n_exp_reg[10]/Q  -type DFF DFF
add mapped point p2/n_exp[11]/q p2/n_exp_reg[11]/Q  -type DFF DFF
add mapped point p2/n_exp[12]/q p2/n_exp_reg[12]/Q  -type DFF DFF
add mapped point p2/n_exp[13]/q p2/n_exp_reg[13]/Q  -type DFF DFF
add mapped point p2/n_exp[14]/q p2/n_exp_reg[14]/Q  -type DFF DFF
add mapped point p2/n_exp[15]/q p2/n_exp_reg[15]/Q  -type DFF DFF
add mapped point p2/n_large_expff[0]/q p2/n_large_expff_reg[0]/Q  -type DFF DFF
add mapped point p2/n_large_expff[1]/q p2/n_large_expff_reg[1]/Q  -type DFF DFF
add mapped point p2/n_large_frac00[0]/q p2/n_large_frac00_reg[0]/Q  -type DFF DFF
add mapped point p2/n_large_frac00[1]/q p2/n_large_frac00_reg[1]/Q  -type DFF DFF
add mapped point p2/n_mode/q p2/n_mode_reg/Q  -type DFF DFF
add mapped point p2/n_op[0]/q p2/n_op_reg[0]/Q  -type DFF DFF
add mapped point p2/n_op[1]/q p2/n_op_reg[1]/Q  -type DFF DFF
add mapped point p2/n_res53[0]/q p2/n_res53_reg[0]/Q  -type DFF DFF
add mapped point p2/n_res53[1]/q p2/n_res53_reg[1]/Q  -type DFF DFF
add mapped point p2/n_res53[2]/q p2/n_res53_reg[2]/Q  -type DFF DFF
add mapped point p2/n_res53[3]/q p2/n_res53_reg[3]/Q  -type DFF DFF
add mapped point p2/n_res53[4]/q p2/n_res53_reg[4]/Q  -type DFF DFF
add mapped point p2/n_res53[5]/q p2/n_res53_reg[5]/Q  -type DFF DFF
add mapped point p2/n_res53[6]/q p2/n_res53_reg[6]/Q  -type DFF DFF
add mapped point p2/n_res53[7]/q p2/n_res53_reg[7]/Q  -type DFF DFF
add mapped point p2/n_res53[8]/q p2/n_res53_reg[8]/Q  -type DFF DFF
add mapped point p2/n_res53[9]/q p2/n_res53_reg[9]/Q  -type DFF DFF
add mapped point p2/n_res53[10]/q p2/n_res53_reg[10]/Q  -type DFF DFF
add mapped point p2/n_res53[11]/q p2/n_res53_reg[11]/Q  -type DFF DFF
add mapped point p2/n_res53[12]/q p2/n_res53_reg[12]/Q  -type DFF DFF
add mapped point p2/n_res53[13]/q p2/n_res53_reg[13]/Q  -type DFF DFF
add mapped point p2/n_res53[14]/q p2/n_res53_reg[14]/Q  -type DFF DFF
add mapped point p2/n_res53[15]/q p2/n_res53_reg[15]/Q  -type DFF DFF
add mapped point p2/n_res53[16]/q p2/n_res53_reg[16]/Q  -type DFF DFF
add mapped point p2/n_res53[17]/q p2/n_res53_reg[17]/Q  -type DFF DFF
add mapped point p2/n_res53[18]/q p2/n_res53_reg[18]/Q  -type DFF DFF
add mapped point p2/n_res53[19]/q p2/n_res53_reg[19]/Q  -type DFF DFF
add mapped point p2/n_res53[20]/q p2/n_res53_reg[20]/Q  -type DFF DFF
add mapped point p2/n_res53[21]/q p2/n_res53_reg[21]/Q  -type DFF DFF
add mapped point p2/n_res53[22]/q p2/n_res53_reg[22]/Q  -type DFF DFF
add mapped point p2/n_res53[23]/q p2/n_res53_reg[23]/Q  -type DFF DFF
add mapped point p2/n_res53[24]/q p2/n_res53_reg[24]/Q  -type DFF DFF
add mapped point p2/n_res53[25]/q p2/n_res53_reg[25]/Q  -type DFF DFF
add mapped point p2/n_res53[26]/q p2/n_res53_reg[26]/Q  -type DFF DFF
add mapped point p2/n_res53[27]/q p2/n_res53_reg[27]/Q  -type DFF DFF
add mapped point p2/n_res53[28]/q p2/n_res53_reg[28]/Q  -type DFF DFF
add mapped point p2/n_res53[29]/q p2/n_res53_reg[29]/Q  -type DFF DFF
add mapped point p2/n_res53[30]/q p2/n_res53_reg[30]/Q  -type DFF DFF
add mapped point p2/n_res53[31]/q p2/n_res53_reg[31]/Q  -type DFF DFF
add mapped point p2/n_res53[32]/q p2/n_res53_reg[32]/Q  -type DFF DFF
add mapped point p2/n_res53[33]/q p2/n_res53_reg[33]/Q  -type DFF DFF
add mapped point p2/n_res53[34]/q p2/n_res53_reg[34]/Q  -type DFF DFF
add mapped point p2/n_res53[35]/q p2/n_res53_reg[35]/Q  -type DFF DFF
add mapped point p2/n_res53[36]/q p2/n_res53_reg[36]/Q  -type DFF DFF
add mapped point p2/n_res53[37]/q p2/n_res53_reg[37]/Q  -type DFF DFF
add mapped point p2/n_res53[38]/q p2/n_res53_reg[38]/Q  -type DFF DFF
add mapped point p2/n_res53[39]/q p2/n_res53_reg[39]/Q  -type DFF DFF
add mapped point p2/n_res53[40]/q p2/n_res53_reg[40]/Q  -type DFF DFF
add mapped point p2/n_res53[41]/q p2/n_res53_reg[41]/Q  -type DFF DFF
add mapped point p2/n_res53[42]/q p2/n_res53_reg[42]/Q  -type DFF DFF
add mapped point p2/n_res53[43]/q p2/n_res53_reg[43]/Q  -type DFF DFF
add mapped point p2/n_res53[44]/q p2/n_res53_reg[44]/Q  -type DFF DFF
add mapped point p2/n_res53[45]/q p2/n_res53_reg[45]/Q  -type DFF DFF
add mapped point p2/n_res53[46]/q p2/n_res53_reg[46]/Q  -type DFF DFF
add mapped point p2/n_res53[47]/q p2/n_res53_reg[47]/Q  -type DFF DFF
add mapped point p2/n_res53[48]/q p2/n_res53_reg[48]/Q  -type DFF DFF
add mapped point p2/n_res53[49]/q p2/n_res53_reg[49]/Q  -type DFF DFF
add mapped point p2/n_res53[50]/q p2/n_res53_reg[50]/Q  -type DFF DFF
add mapped point p2/n_res53[51]/q p2/n_res53_reg[51]/Q  -type DFF DFF
add mapped point p2/n_res53[52]/q p2/n_res53_reg[52]/Q  -type DFF DFF
add mapped point p2/n_small_expff[0]/q p2/n_small_expff_reg[0]/Q  -type DFF DFF
add mapped point p2/n_small_expff[1]/q p2/n_small_expff_reg[1]/Q  -type DFF DFF
add mapped point p2/n_small_frac00[0]/q p2/n_small_frac00_reg[0]/Q  -type DFF DFF
add mapped point p2/n_small_frac00[1]/q p2/n_small_frac00_reg[1]/Q  -type DFF DFF
add mapped point p3/r_Ls[0]/q p3/r_Ls_reg[0]/Q  -type DFF DFF
add mapped point p3/r_Ls[1]/q p3/r_Ls_reg[1]/Q  -type DFF DFF
add mapped point p3/r_exp[0]/q p3/r_exp_reg[0]/Q  -type DFF DFF
add mapped point p3/r_exp[1]/q p3/r_exp_reg[1]/Q  -type DFF DFF
add mapped point p3/r_exp[2]/q p3/r_exp_reg[2]/Q  -type DFF DFF
add mapped point p3/r_exp[3]/q p3/r_exp_reg[3]/Q  -type DFF DFF
add mapped point p3/r_exp[4]/q p3/r_exp_reg[4]/Q  -type DFF DFF
add mapped point p3/r_exp[5]/q p3/r_exp_reg[5]/Q  -type DFF DFF
add mapped point p3/r_exp[6]/q p3/r_exp_reg[6]/Q  -type DFF DFF
add mapped point p3/r_exp[7]/q p3/r_exp_reg[7]/Q  -type DFF DFF
add mapped point p3/r_exp[8]/q p3/r_exp_reg[8]/Q  -type DFF DFF
add mapped point p3/r_exp[9]/q p3/r_exp_reg[9]/Q  -type DFF DFF
add mapped point p3/r_exp[10]/q p3/r_exp_reg[10]/Q  -type DFF DFF
add mapped point p3/r_exp[11]/q p3/r_exp_reg[11]/Q  -type DFF DFF
add mapped point p3/r_exp[12]/q p3/r_exp_reg[12]/Q  -type DFF DFF
add mapped point p3/r_exp[13]/q p3/r_exp_reg[13]/Q  -type DFF DFF
add mapped point p3/r_exp[14]/q p3/r_exp_reg[14]/Q  -type DFF DFF
add mapped point p3/r_exp[15]/q p3/r_exp_reg[15]/Q  -type DFF DFF
add mapped point p3/r_large_expff[0]/q p3/r_large_expff_reg[0]/Q  -type DFF DFF
add mapped point p3/r_large_expff[1]/q p3/r_large_expff_reg[1]/Q  -type DFF DFF
add mapped point p3/r_large_frac00[0]/q p3/r_large_frac00_reg[0]/Q  -type DFF DFF
add mapped point p3/r_large_frac00[1]/q p3/r_large_frac00_reg[1]/Q  -type DFF DFF
add mapped point p3/r_mode/q p3/r_mode_reg/Q  -type DFF DFF
add mapped point p3/r_o_res53[0]/q p3/r_o_res53_reg[0]/Q  -type DFF DFF
add mapped point p3/r_o_res53[1]/q p3/r_o_res53_reg[1]/Q  -type DFF DFF
add mapped point p3/r_o_res53[2]/q p3/r_o_res53_reg[2]/Q  -type DFF DFF
add mapped point p3/r_o_res53[3]/q p3/r_o_res53_reg[3]/Q  -type DFF DFF
add mapped point p3/r_o_res53[4]/q p3/r_o_res53_reg[4]/Q  -type DFF DFF
add mapped point p3/r_o_res53[5]/q p3/r_o_res53_reg[5]/Q  -type DFF DFF
add mapped point p3/r_o_res53[6]/q p3/r_o_res53_reg[6]/Q  -type DFF DFF
add mapped point p3/r_o_res53[7]/q p3/r_o_res53_reg[7]/Q  -type DFF DFF
add mapped point p3/r_o_res53[8]/q p3/r_o_res53_reg[8]/Q  -type DFF DFF
add mapped point p3/r_o_res53[9]/q p3/r_o_res53_reg[9]/Q  -type DFF DFF
add mapped point p3/r_o_res53[10]/q p3/r_o_res53_reg[10]/Q  -type DFF DFF
add mapped point p3/r_o_res53[11]/q p3/r_o_res53_reg[11]/Q  -type DFF DFF
add mapped point p3/r_o_res53[12]/q p3/r_o_res53_reg[12]/Q  -type DFF DFF
add mapped point p3/r_o_res53[13]/q p3/r_o_res53_reg[13]/Q  -type DFF DFF
add mapped point p3/r_o_res53[14]/q p3/r_o_res53_reg[14]/Q  -type DFF DFF
add mapped point p3/r_o_res53[15]/q p3/r_o_res53_reg[15]/Q  -type DFF DFF
add mapped point p3/r_o_res53[16]/q p3/r_o_res53_reg[16]/Q  -type DFF DFF
add mapped point p3/r_o_res53[17]/q p3/r_o_res53_reg[17]/Q  -type DFF DFF
add mapped point p3/r_o_res53[18]/q p3/r_o_res53_reg[18]/Q  -type DFF DFF
add mapped point p3/r_o_res53[19]/q p3/r_o_res53_reg[19]/Q  -type DFF DFF
add mapped point p3/r_o_res53[20]/q p3/r_o_res53_reg[20]/Q  -type DFF DFF
add mapped point p3/r_o_res53[21]/q p3/r_o_res53_reg[21]/Q  -type DFF DFF
add mapped point p3/r_o_res53[22]/q p3/r_o_res53_reg[22]/Q  -type DFF DFF
add mapped point p3/r_o_res53[23]/q p3/r_o_res53_reg[23]/Q  -type DFF DFF
add mapped point p3/r_o_res53[24]/q p3/r_o_res53_reg[24]/Q  -type DFF DFF
add mapped point p3/r_o_res53[25]/q p3/r_o_res53_reg[25]/Q  -type DFF DFF
add mapped point p3/r_o_res53[26]/q p3/r_o_res53_reg[26]/Q  -type DFF DFF
add mapped point p3/r_o_res53[27]/q p3/r_o_res53_reg[27]/Q  -type DFF DFF
add mapped point p3/r_o_res53[28]/q p3/r_o_res53_reg[28]/Q  -type DFF DFF
add mapped point p3/r_o_res53[29]/q p3/r_o_res53_reg[29]/Q  -type DFF DFF
add mapped point p3/r_o_res53[30]/q p3/r_o_res53_reg[30]/Q  -type DFF DFF
add mapped point p3/r_o_res53[31]/q p3/r_o_res53_reg[31]/Q  -type DFF DFF
add mapped point p3/r_o_res53[32]/q p3/r_o_res53_reg[32]/Q  -type DFF DFF
add mapped point p3/r_o_res53[33]/q p3/r_o_res53_reg[33]/Q  -type DFF DFF
add mapped point p3/r_o_res53[34]/q p3/r_o_res53_reg[34]/Q  -type DFF DFF
add mapped point p3/r_o_res53[35]/q p3/r_o_res53_reg[35]/Q  -type DFF DFF
add mapped point p3/r_o_res53[36]/q p3/r_o_res53_reg[36]/Q  -type DFF DFF
add mapped point p3/r_o_res53[37]/q p3/r_o_res53_reg[37]/Q  -type DFF DFF
add mapped point p3/r_o_res53[38]/q p3/r_o_res53_reg[38]/Q  -type DFF DFF
add mapped point p3/r_o_res53[39]/q p3/r_o_res53_reg[39]/Q  -type DFF DFF
add mapped point p3/r_o_res53[40]/q p3/r_o_res53_reg[40]/Q  -type DFF DFF
add mapped point p3/r_o_res53[41]/q p3/r_o_res53_reg[41]/Q  -type DFF DFF
add mapped point p3/r_o_res53[42]/q p3/r_o_res53_reg[42]/Q  -type DFF DFF
add mapped point p3/r_o_res53[43]/q p3/r_o_res53_reg[43]/Q  -type DFF DFF
add mapped point p3/r_o_res53[44]/q p3/r_o_res53_reg[44]/Q  -type DFF DFF
add mapped point p3/r_o_res53[45]/q p3/r_o_res53_reg[45]/Q  -type DFF DFF
add mapped point p3/r_o_res53[46]/q p3/r_o_res53_reg[46]/Q  -type DFF DFF
add mapped point p3/r_o_res53[47]/q p3/r_o_res53_reg[47]/Q  -type DFF DFF
add mapped point p3/r_o_res53[48]/q p3/r_o_res53_reg[48]/Q  -type DFF DFF
add mapped point p3/r_o_res53[49]/q p3/r_o_res53_reg[49]/Q  -type DFF DFF
add mapped point p3/r_o_res53[50]/q p3/r_o_res53_reg[50]/Q  -type DFF DFF
add mapped point p3/r_o_res53[51]/q p3/r_o_res53_reg[51]/Q  -type DFF DFF
add mapped point p3/r_o_res53[52]/q p3/r_o_res53_reg[52]/Q  -type DFF DFF
add mapped point p3/r_op[0]/q p3/r_op_reg[0]/Q  -type DFF DFF
add mapped point p3/r_op[1]/q p3/r_op_reg[1]/Q  -type DFF DFF
add mapped point p3/r_res53[0]/q p3/r_res53_reg[0]/Q  -type DFF DFF
add mapped point p3/r_res53[1]/q p3/r_res53_reg[1]/Q  -type DFF DFF
add mapped point p3/r_res53[2]/q p3/r_res53_reg[2]/Q  -type DFF DFF
add mapped point p3/r_res53[3]/q p3/r_res53_reg[3]/Q  -type DFF DFF
add mapped point p3/r_res53[4]/q p3/r_res53_reg[4]/Q  -type DFF DFF
add mapped point p3/r_res53[5]/q p3/r_res53_reg[5]/Q  -type DFF DFF
add mapped point p3/r_res53[6]/q p3/r_res53_reg[6]/Q  -type DFF DFF
add mapped point p3/r_res53[7]/q p3/r_res53_reg[7]/Q  -type DFF DFF
add mapped point p3/r_res53[8]/q p3/r_res53_reg[8]/Q  -type DFF DFF
add mapped point p3/r_res53[9]/q p3/r_res53_reg[9]/Q  -type DFF DFF
add mapped point p3/r_res53[10]/q p3/r_res53_reg[10]/Q  -type DFF DFF
add mapped point p3/r_res53[11]/q p3/r_res53_reg[11]/Q  -type DFF DFF
add mapped point p3/r_res53[12]/q p3/r_res53_reg[12]/Q  -type DFF DFF
add mapped point p3/r_res53[13]/q p3/r_res53_reg[13]/Q  -type DFF DFF
add mapped point p3/r_res53[14]/q p3/r_res53_reg[14]/Q  -type DFF DFF
add mapped point p3/r_res53[15]/q p3/r_res53_reg[15]/Q  -type DFF DFF
add mapped point p3/r_res53[16]/q p3/r_res53_reg[16]/Q  -type DFF DFF
add mapped point p3/r_res53[17]/q p3/r_res53_reg[17]/Q  -type DFF DFF
add mapped point p3/r_res53[18]/q p3/r_res53_reg[18]/Q  -type DFF DFF
add mapped point p3/r_res53[19]/q p3/r_res53_reg[19]/Q  -type DFF DFF
add mapped point p3/r_res53[20]/q p3/r_res53_reg[20]/Q  -type DFF DFF
add mapped point p3/r_res53[21]/q p3/r_res53_reg[21]/Q  -type DFF DFF
add mapped point p3/r_res53[22]/q p3/r_res53_reg[22]/Q  -type DFF DFF
add mapped point p3/r_res53[23]/q p3/r_res53_reg[23]/Q  -type DFF DFF
add mapped point p3/r_res53[24]/q p3/r_res53_reg[24]/Q  -type DFF DFF
add mapped point p3/r_res53[25]/q p3/r_res53_reg[25]/Q  -type DFF DFF
add mapped point p3/r_res53[26]/q p3/r_res53_reg[26]/Q  -type DFF DFF
add mapped point p3/r_res53[27]/q p3/r_res53_reg[27]/Q  -type DFF DFF
add mapped point p3/r_res53[28]/q p3/r_res53_reg[28]/Q  -type DFF DFF
add mapped point p3/r_res53[29]/q p3/r_res53_reg[29]/Q  -type DFF DFF
add mapped point p3/r_res53[30]/q p3/r_res53_reg[30]/Q  -type DFF DFF
add mapped point p3/r_res53[31]/q p3/r_res53_reg[31]/Q  -type DFF DFF
add mapped point p3/r_res53[32]/q p3/r_res53_reg[32]/Q  -type DFF DFF
add mapped point p3/r_res53[33]/q p3/r_res53_reg[33]/Q  -type DFF DFF
add mapped point p3/r_res53[34]/q p3/r_res53_reg[34]/Q  -type DFF DFF
add mapped point p3/r_res53[35]/q p3/r_res53_reg[35]/Q  -type DFF DFF
add mapped point p3/r_res53[36]/q p3/r_res53_reg[36]/Q  -type DFF DFF
add mapped point p3/r_res53[37]/q p3/r_res53_reg[37]/Q  -type DFF DFF
add mapped point p3/r_res53[38]/q p3/r_res53_reg[38]/Q  -type DFF DFF
add mapped point p3/r_res53[39]/q p3/r_res53_reg[39]/Q  -type DFF DFF
add mapped point p3/r_res53[40]/q p3/r_res53_reg[40]/Q  -type DFF DFF
add mapped point p3/r_res53[41]/q p3/r_res53_reg[41]/Q  -type DFF DFF
add mapped point p3/r_res53[42]/q p3/r_res53_reg[42]/Q  -type DFF DFF
add mapped point p3/r_res53[43]/q p3/r_res53_reg[43]/Q  -type DFF DFF
add mapped point p3/r_res53[44]/q p3/r_res53_reg[44]/Q  -type DFF DFF
add mapped point p3/r_res53[45]/q p3/r_res53_reg[45]/Q  -type DFF DFF
add mapped point p3/r_res53[46]/q p3/r_res53_reg[46]/Q  -type DFF DFF
add mapped point p3/r_res53[47]/q p3/r_res53_reg[47]/Q  -type DFF DFF
add mapped point p3/r_res53[48]/q p3/r_res53_reg[48]/Q  -type DFF DFF
add mapped point p3/r_res53[49]/q p3/r_res53_reg[49]/Q  -type DFF DFF
add mapped point p3/r_res53[50]/q p3/r_res53_reg[50]/Q  -type DFF DFF
add mapped point p3/r_res53[51]/q p3/r_res53_reg[51]/Q  -type DFF DFF
add mapped point p3/r_small_expff[0]/q p3/r_small_expff_reg[0]/Q  -type DFF DFF
add mapped point p3/r_small_expff[1]/q p3/r_small_expff_reg[1]/Q  -type DFF DFF
add mapped point p3/r_small_frac00[0]/q p3/r_small_frac00_reg[0]/Q  -type DFF DFF
add mapped point p3/r_small_frac00[1]/q p3/r_small_frac00_reg[1]/Q  -type DFF DFF
add mapped point p3/r_z24[0]/q p3/r_z24_reg[0]/Q  -type DFF DFF
add mapped point p3/r_z24[1]/q p3/r_z24_reg[1]/Q  -type DFF DFF
add mapped point p3/r_z24[2]/q p3/r_z24_reg[2]/Q  -type DFF DFF
add mapped point p3/r_z24[3]/q p3/r_z24_reg[3]/Q  -type DFF DFF
add mapped point p3/r_z24[4]/q p3/r_z24_reg[4]/Q  -type DFF DFF
add mapped point p3/r_z29[0]/q p3/r_z29_reg[0]/Q  -type DFF DFF
add mapped point p3/r_z29[1]/q p3/r_z29_reg[1]/Q  -type DFF DFF
add mapped point p3/r_z29[2]/q p3/r_z29_reg[2]/Q  -type DFF DFF
add mapped point p3/r_z29[3]/q p3/r_z29_reg[3]/Q  -type DFF DFF
add mapped point p3/r_z29[4]/q p3/r_z29_reg[4]/Q  -type DFF DFF
add mapped point p3/r_z52[0]/q p3/r_z52_reg[0]/Q  -type DFF DFF
add mapped point p3/r_z52[1]/q p3/r_z52_reg[1]/Q  -type DFF DFF
add mapped point p3/r_z52[2]/q p3/r_z52_reg[2]/Q  -type DFF DFF
add mapped point p3/r_z52[3]/q p3/r_z52_reg[3]/Q  -type DFF DFF
add mapped point p3/r_z52[4]/q p3/r_z52_reg[4]/Q  -type DFF DFF
add mapped point p3/r_z52[5]/q p3/r_z52_reg[5]/Q  -type DFF DFF
add mapped point p4/ou_Ls[0]/q p4/ou_Ls_reg[0]/Q  -type DFF DFF
add mapped point p4/ou_Ls[1]/q p4/ou_Ls_reg[1]/Q  -type DFF DFF
add mapped point p4/ou_mode/q p4/ou_mode_reg/Q  -type DFF DFF
add mapped point p4/ou_res_expo[0]/q p4/ou_res_expo_reg[0]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[1]/q p4/ou_res_expo_reg[1]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[2]/q p4/ou_res_expo_reg[2]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[3]/q p4/ou_res_expo_reg[3]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[4]/q p4/ou_res_expo_reg[4]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[5]/q p4/ou_res_expo_reg[5]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[6]/q p4/ou_res_expo_reg[6]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[7]/q p4/ou_res_expo_reg[7]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[8]/q p4/ou_res_expo_reg[8]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[9]/q p4/ou_res_expo_reg[9]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[10]/q p4/ou_res_expo_reg[10]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[11]/q p4/ou_res_expo_reg[11]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[12]/q p4/ou_res_expo_reg[12]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[13]/q p4/ou_res_expo_reg[13]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[14]/q p4/ou_res_expo_reg[14]/Q  -type DFF DFF
add mapped point p4/ou_res_expo[15]/q p4/ou_res_expo_reg[15]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[0]/q p4/ou_res_frac_reg[0]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[1]/q p4/ou_res_frac_reg[1]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[2]/q p4/ou_res_frac_reg[2]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[3]/q p4/ou_res_frac_reg[3]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[4]/q p4/ou_res_frac_reg[4]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[5]/q p4/ou_res_frac_reg[5]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[6]/q p4/ou_res_frac_reg[6]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[7]/q p4/ou_res_frac_reg[7]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[8]/q p4/ou_res_frac_reg[8]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[9]/q p4/ou_res_frac_reg[9]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[10]/q p4/ou_res_frac_reg[10]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[11]/q p4/ou_res_frac_reg[11]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[12]/q p4/ou_res_frac_reg[12]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[13]/q p4/ou_res_frac_reg[13]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[14]/q p4/ou_res_frac_reg[14]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[15]/q p4/ou_res_frac_reg[15]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[16]/q p4/ou_res_frac_reg[16]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[17]/q p4/ou_res_frac_reg[17]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[18]/q p4/ou_res_frac_reg[18]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[19]/q p4/ou_res_frac_reg[19]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[20]/q p4/ou_res_frac_reg[20]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[21]/q p4/ou_res_frac_reg[21]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[22]/q p4/ou_res_frac_reg[22]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[23]/q p4/ou_res_frac_reg[23]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[24]/q p4/ou_res_frac_reg[24]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[25]/q p4/ou_res_frac_reg[25]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[26]/q p4/ou_res_frac_reg[26]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[27]/q p4/ou_res_frac_reg[27]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[28]/q p4/ou_res_frac_reg[28]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[29]/q p4/ou_res_frac_reg[29]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[30]/q p4/ou_res_frac_reg[30]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[31]/q p4/ou_res_frac_reg[31]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[32]/q p4/ou_res_frac_reg[32]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[33]/q p4/ou_res_frac_reg[33]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[34]/q p4/ou_res_frac_reg[34]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[35]/q p4/ou_res_frac_reg[35]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[36]/q p4/ou_res_frac_reg[36]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[37]/q p4/ou_res_frac_reg[37]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[38]/q p4/ou_res_frac_reg[38]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[39]/q p4/ou_res_frac_reg[39]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[40]/q p4/ou_res_frac_reg[40]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[41]/q p4/ou_res_frac_reg[41]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[42]/q p4/ou_res_frac_reg[42]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[43]/q p4/ou_res_frac_reg[43]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[44]/q p4/ou_res_frac_reg[44]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[45]/q p4/ou_res_frac_reg[45]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[46]/q p4/ou_res_frac_reg[46]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[47]/q p4/ou_res_frac_reg[47]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[48]/q p4/ou_res_frac_reg[48]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[49]/q p4/ou_res_frac_reg[49]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[50]/q p4/ou_res_frac_reg[50]/Q  -type DFF DFF
add mapped point p4/ou_res_frac[51]/q p4/ou_res_frac_reg[51]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
