
//input ports
add mapped point i_mode i_mode -type PI PI
add mapped point i_A[63] i_A[63] -type PI PI
add mapped point i_A[62] i_A[62] -type PI PI
add mapped point i_A[61] i_A[61] -type PI PI
add mapped point i_A[60] i_A[60] -type PI PI
add mapped point i_A[59] i_A[59] -type PI PI
add mapped point i_A[58] i_A[58] -type PI PI
add mapped point i_A[57] i_A[57] -type PI PI
add mapped point i_A[56] i_A[56] -type PI PI
add mapped point i_A[55] i_A[55] -type PI PI
add mapped point i_A[54] i_A[54] -type PI PI
add mapped point i_A[53] i_A[53] -type PI PI
add mapped point i_A[52] i_A[52] -type PI PI
add mapped point i_A[51] i_A[51] -type PI PI
add mapped point i_A[50] i_A[50] -type PI PI
add mapped point i_A[49] i_A[49] -type PI PI
add mapped point i_A[48] i_A[48] -type PI PI
add mapped point i_A[47] i_A[47] -type PI PI
add mapped point i_A[46] i_A[46] -type PI PI
add mapped point i_A[45] i_A[45] -type PI PI
add mapped point i_A[44] i_A[44] -type PI PI
add mapped point i_A[43] i_A[43] -type PI PI
add mapped point i_A[42] i_A[42] -type PI PI
add mapped point i_A[41] i_A[41] -type PI PI
add mapped point i_A[40] i_A[40] -type PI PI
add mapped point i_A[39] i_A[39] -type PI PI
add mapped point i_A[38] i_A[38] -type PI PI
add mapped point i_A[37] i_A[37] -type PI PI
add mapped point i_A[36] i_A[36] -type PI PI
add mapped point i_A[35] i_A[35] -type PI PI
add mapped point i_A[34] i_A[34] -type PI PI
add mapped point i_A[33] i_A[33] -type PI PI
add mapped point i_A[32] i_A[32] -type PI PI
add mapped point i_A[31] i_A[31] -type PI PI
add mapped point i_A[30] i_A[30] -type PI PI
add mapped point i_A[29] i_A[29] -type PI PI
add mapped point i_A[28] i_A[28] -type PI PI
add mapped point i_A[27] i_A[27] -type PI PI
add mapped point i_A[26] i_A[26] -type PI PI
add mapped point i_A[25] i_A[25] -type PI PI
add mapped point i_A[24] i_A[24] -type PI PI
add mapped point i_A[23] i_A[23] -type PI PI
add mapped point i_A[22] i_A[22] -type PI PI
add mapped point i_A[21] i_A[21] -type PI PI
add mapped point i_A[20] i_A[20] -type PI PI
add mapped point i_A[19] i_A[19] -type PI PI
add mapped point i_A[18] i_A[18] -type PI PI
add mapped point i_A[17] i_A[17] -type PI PI
add mapped point i_A[16] i_A[16] -type PI PI
add mapped point i_A[15] i_A[15] -type PI PI
add mapped point i_A[14] i_A[14] -type PI PI
add mapped point i_A[13] i_A[13] -type PI PI
add mapped point i_A[12] i_A[12] -type PI PI
add mapped point i_A[11] i_A[11] -type PI PI
add mapped point i_A[10] i_A[10] -type PI PI
add mapped point i_A[9] i_A[9] -type PI PI
add mapped point i_A[8] i_A[8] -type PI PI
add mapped point i_A[7] i_A[7] -type PI PI
add mapped point i_A[6] i_A[6] -type PI PI
add mapped point i_A[5] i_A[5] -type PI PI
add mapped point i_A[4] i_A[4] -type PI PI
add mapped point i_A[3] i_A[3] -type PI PI
add mapped point i_A[2] i_A[2] -type PI PI
add mapped point i_A[1] i_A[1] -type PI PI
add mapped point i_A[0] i_A[0] -type PI PI
add mapped point i_B[63] i_B[63] -type PI PI
add mapped point i_B[62] i_B[62] -type PI PI
add mapped point i_B[61] i_B[61] -type PI PI
add mapped point i_B[60] i_B[60] -type PI PI
add mapped point i_B[59] i_B[59] -type PI PI
add mapped point i_B[58] i_B[58] -type PI PI
add mapped point i_B[57] i_B[57] -type PI PI
add mapped point i_B[56] i_B[56] -type PI PI
add mapped point i_B[55] i_B[55] -type PI PI
add mapped point i_B[54] i_B[54] -type PI PI
add mapped point i_B[53] i_B[53] -type PI PI
add mapped point i_B[52] i_B[52] -type PI PI
add mapped point i_B[51] i_B[51] -type PI PI
add mapped point i_B[50] i_B[50] -type PI PI
add mapped point i_B[49] i_B[49] -type PI PI
add mapped point i_B[48] i_B[48] -type PI PI
add mapped point i_B[47] i_B[47] -type PI PI
add mapped point i_B[46] i_B[46] -type PI PI
add mapped point i_B[45] i_B[45] -type PI PI
add mapped point i_B[44] i_B[44] -type PI PI
add mapped point i_B[43] i_B[43] -type PI PI
add mapped point i_B[42] i_B[42] -type PI PI
add mapped point i_B[41] i_B[41] -type PI PI
add mapped point i_B[40] i_B[40] -type PI PI
add mapped point i_B[39] i_B[39] -type PI PI
add mapped point i_B[38] i_B[38] -type PI PI
add mapped point i_B[37] i_B[37] -type PI PI
add mapped point i_B[36] i_B[36] -type PI PI
add mapped point i_B[35] i_B[35] -type PI PI
add mapped point i_B[34] i_B[34] -type PI PI
add mapped point i_B[33] i_B[33] -type PI PI
add mapped point i_B[32] i_B[32] -type PI PI
add mapped point i_B[31] i_B[31] -type PI PI
add mapped point i_B[30] i_B[30] -type PI PI
add mapped point i_B[29] i_B[29] -type PI PI
add mapped point i_B[28] i_B[28] -type PI PI
add mapped point i_B[27] i_B[27] -type PI PI
add mapped point i_B[26] i_B[26] -type PI PI
add mapped point i_B[25] i_B[25] -type PI PI
add mapped point i_B[24] i_B[24] -type PI PI
add mapped point i_B[23] i_B[23] -type PI PI
add mapped point i_B[22] i_B[22] -type PI PI
add mapped point i_B[21] i_B[21] -type PI PI
add mapped point i_B[20] i_B[20] -type PI PI
add mapped point i_B[19] i_B[19] -type PI PI
add mapped point i_B[18] i_B[18] -type PI PI
add mapped point i_B[17] i_B[17] -type PI PI
add mapped point i_B[16] i_B[16] -type PI PI
add mapped point i_B[15] i_B[15] -type PI PI
add mapped point i_B[14] i_B[14] -type PI PI
add mapped point i_B[13] i_B[13] -type PI PI
add mapped point i_B[12] i_B[12] -type PI PI
add mapped point i_B[11] i_B[11] -type PI PI
add mapped point i_B[10] i_B[10] -type PI PI
add mapped point i_B[9] i_B[9] -type PI PI
add mapped point i_B[8] i_B[8] -type PI PI
add mapped point i_B[7] i_B[7] -type PI PI
add mapped point i_B[6] i_B[6] -type PI PI
add mapped point i_B[5] i_B[5] -type PI PI
add mapped point i_B[4] i_B[4] -type PI PI
add mapped point i_B[3] i_B[3] -type PI PI
add mapped point i_B[2] i_B[2] -type PI PI
add mapped point i_B[1] i_B[1] -type PI PI
add mapped point i_B[0] i_B[0] -type PI PI

//output ports
add mapped point o_res[63] o_res[63] -type PO PO
add mapped point o_res[62] o_res[62] -type PO PO
add mapped point o_res[61] o_res[61] -type PO PO
add mapped point o_res[60] o_res[60] -type PO PO
add mapped point o_res[59] o_res[59] -type PO PO
add mapped point o_res[58] o_res[58] -type PO PO
add mapped point o_res[57] o_res[57] -type PO PO
add mapped point o_res[56] o_res[56] -type PO PO
add mapped point o_res[55] o_res[55] -type PO PO
add mapped point o_res[54] o_res[54] -type PO PO
add mapped point o_res[53] o_res[53] -type PO PO
add mapped point o_res[52] o_res[52] -type PO PO
add mapped point o_res[51] o_res[51] -type PO PO
add mapped point o_res[50] o_res[50] -type PO PO
add mapped point o_res[49] o_res[49] -type PO PO
add mapped point o_res[48] o_res[48] -type PO PO
add mapped point o_res[47] o_res[47] -type PO PO
add mapped point o_res[46] o_res[46] -type PO PO
add mapped point o_res[45] o_res[45] -type PO PO
add mapped point o_res[44] o_res[44] -type PO PO
add mapped point o_res[43] o_res[43] -type PO PO
add mapped point o_res[42] o_res[42] -type PO PO
add mapped point o_res[41] o_res[41] -type PO PO
add mapped point o_res[40] o_res[40] -type PO PO
add mapped point o_res[39] o_res[39] -type PO PO
add mapped point o_res[38] o_res[38] -type PO PO
add mapped point o_res[37] o_res[37] -type PO PO
add mapped point o_res[36] o_res[36] -type PO PO
add mapped point o_res[35] o_res[35] -type PO PO
add mapped point o_res[34] o_res[34] -type PO PO
add mapped point o_res[33] o_res[33] -type PO PO
add mapped point o_res[32] o_res[32] -type PO PO
add mapped point o_res[31] o_res[31] -type PO PO
add mapped point o_res[30] o_res[30] -type PO PO
add mapped point o_res[29] o_res[29] -type PO PO
add mapped point o_res[28] o_res[28] -type PO PO
add mapped point o_res[27] o_res[27] -type PO PO
add mapped point o_res[26] o_res[26] -type PO PO
add mapped point o_res[25] o_res[25] -type PO PO
add mapped point o_res[24] o_res[24] -type PO PO
add mapped point o_res[23] o_res[23] -type PO PO
add mapped point o_res[22] o_res[22] -type PO PO
add mapped point o_res[21] o_res[21] -type PO PO
add mapped point o_res[20] o_res[20] -type PO PO
add mapped point o_res[19] o_res[19] -type PO PO
add mapped point o_res[18] o_res[18] -type PO PO
add mapped point o_res[17] o_res[17] -type PO PO
add mapped point o_res[16] o_res[16] -type PO PO
add mapped point o_res[15] o_res[15] -type PO PO
add mapped point o_res[14] o_res[14] -type PO PO
add mapped point o_res[13] o_res[13] -type PO PO
add mapped point o_res[12] o_res[12] -type PO PO
add mapped point o_res[11] o_res[11] -type PO PO
add mapped point o_res[10] o_res[10] -type PO PO
add mapped point o_res[9] o_res[9] -type PO PO
add mapped point o_res[8] o_res[8] -type PO PO
add mapped point o_res[7] o_res[7] -type PO PO
add mapped point o_res[6] o_res[6] -type PO PO
add mapped point o_res[5] o_res[5] -type PO PO
add mapped point o_res[4] o_res[4] -type PO PO
add mapped point o_res[3] o_res[3] -type PO PO
add mapped point o_res[2] o_res[2] -type PO PO
add mapped point o_res[1] o_res[1] -type PO PO
add mapped point o_res[0] o_res[0] -type PO PO

//inout ports




//Sequential Pins



//Black Boxes



//Empty Modules as Blackboxes
